"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.models.components import (
    campaignversionworkflow as components_campaignversionworkflow,
    httpmetadata as components_httpmetadata,
)
from ttd_workflows.types import BaseModel
from ttd_workflows.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCampaignVersionRequestTypedDict(TypedDict):
    id: str


class GetCampaignVersionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetCampaignVersionResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    campaign_version_workflow: NotRequired[
        components_campaignversionworkflow.CampaignVersionWorkflowTypedDict
    ]
    r"""OK"""


class GetCampaignVersionResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    campaign_version_workflow: Optional[
        components_campaignversionworkflow.CampaignVersionWorkflow
    ] = None
    r"""OK"""
