"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.models.components import (
    graphqlqueryjobresponse as components_graphqlqueryjobresponse,
    httpmetadata as components_httpmetadata,
)
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SubmitGraphQlQueryJobResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    graph_ql_query_job_response: NotRequired[
        components_graphqlqueryjobresponse.GraphQlQueryJobResponseTypedDict
    ]
    r"""OK"""


class SubmitGraphQlQueryJobResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    graph_ql_query_job_response: Optional[
        components_graphqlqueryjobresponse.GraphQlQueryJobResponse
    ] = None
    r"""OK"""
