"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.models.components import (
    campaignpayload as components_campaignpayload,
    httpmetadata as components_httpmetadata,
)
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateCampaignResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    campaign_payload: NotRequired[components_campaignpayload.CampaignPayloadTypedDict]
    r"""OK"""


class UpdateCampaignResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    campaign_payload: Optional[components_campaignpayload.CampaignPayload] = None
    r"""OK"""
