"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.models.components import (
    adgrouppayload as components_adgrouppayload,
    httpmetadata as components_httpmetadata,
)
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateAdGroupResponseTypedDict(TypedDict):
    http_meta: components_httpmetadata.HTTPMetadataTypedDict
    ad_group_payload: NotRequired[components_adgrouppayload.AdGroupPayloadTypedDict]
    r"""OK"""


class UpdateAdGroupResponse(BaseModel):
    http_meta: Annotated[
        Optional[components_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None

    ad_group_payload: Optional[components_adgrouppayload.AdGroupPayload] = None
    r"""OK"""
