"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "ttd-workflows"
__version__: str = "0.4.2"
__openapi_doc_version__: str = "v1"
__gen_version__: str = "2.610.0"
__user_agent__: str = "speakeasy-sdk/python 0.4.2 2.610.0 v1 ttd-workflows"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
