"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupWorkflowNewFrequencyConfigInputTypedDict(TypedDict):
    counter_name: Nullable[str]
    frequency_cap: NotRequired[Nullable[int]]
    frequency_goal: NotRequired[Nullable[int]]
    reset_interval_in_minutes: NotRequired[int]


class AdGroupWorkflowNewFrequencyConfigInput(BaseModel):
    counter_name: Annotated[Nullable[str], pydantic.Field(alias="counterName")]

    frequency_cap: Annotated[
        OptionalNullable[int], pydantic.Field(alias="frequencyCap")
    ] = UNSET

    frequency_goal: Annotated[
        OptionalNullable[int], pydantic.Field(alias="frequencyGoal")
    ] = UNSET

    reset_interval_in_minutes: Annotated[
        Optional[int], pydantic.Field(alias="resetIntervalInMinutes")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["frequencyCap", "frequencyGoal", "resetIntervalInMinutes"]
        nullable_fields = ["counterName", "frequencyCap", "frequencyGoal"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
