"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import NotRequired, TypedDict


class VariablesTypedDict(TypedDict):
    r"""Variables to substitute into the query."""


class Variables(BaseModel):
    r"""Variables to substitute into the query."""


class GraphQLRequestInputTypedDict(TypedDict):
    r"""Required fields for executing a GraphQL query"""

    request: str
    r"""The GraphQL query to execute."""
    variables: NotRequired[Nullable[VariablesTypedDict]]
    r"""Variables to substitute into the query."""


class GraphQLRequestInput(BaseModel):
    r"""Required fields for executing a GraphQL query"""

    request: str
    r"""The GraphQL query to execute."""

    variables: OptionalNullable[Variables] = UNSET
    r"""Variables to substitute into the query."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["variables"]
        nullable_fields = ["variables"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
