"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .adgroupadvancedsettingsinput import (
    AdGroupAdvancedSettingsInput,
    AdGroupAdvancedSettingsInputTypedDict,
)
from .adgroupassociatebidlist import (
    AdGroupAssociateBidList,
    AdGroupAssociateBidListTypedDict,
)
from .adgroupassociatebidlistinput import (
    AdGroupAssociateBidListInput,
    AdGroupAssociateBidListInputTypedDict,
)
from .adgroupaudiencetargeting import (
    AdGroupAudienceTargeting,
    AdGroupAudienceTargetingTypedDict,
)
from .adgroupaudiencetargetinginput import (
    AdGroupAudienceTargetingInput,
    AdGroupAudienceTargetingInputTypedDict,
)
from .adgroupbudget import AdGroupBudget, AdGroupBudgetTypedDict
from .adgroupbudgetinput import AdGroupBudgetInput, AdGroupBudgetInputTypedDict
from .adgroupchannel import AdGroupChannel
from .adgroupcomscoresettings import (
    AdGroupComscoreSettings,
    AdGroupComscoreSettingsTypedDict,
)
from .adgroupcomscoresettingsinput import (
    AdGroupComscoreSettingsInput,
    AdGroupComscoreSettingsInputTypedDict,
)
from .adgroupcontracttargeting import (
    AdGroupContractTargeting,
    AdGroupContractTargetingTypedDict,
)
from .adgroupcontracttargetinginput import (
    AdGroupContractTargetingInput,
    AdGroupContractTargetingInputTypedDict,
)
from .adgroupflight import AdGroupFlight, AdGroupFlightTypedDict
from .adgroupflightinput import AdGroupFlightInput, AdGroupFlightInputTypedDict
from .adgroupfunnellocation import AdGroupFunnelLocation
from .adgroupkoaoptimizationsettings import (
    AdGroupKoaOptimizationSettings,
    AdGroupKoaOptimizationSettingsTypedDict,
)
from .adgroupkoaoptimizationsettingsinput import (
    AdGroupKoaOptimizationSettingsInput,
    AdGroupKoaOptimizationSettingsInputTypedDict,
)
from .adgroupnewfrequencyconfiginput import (
    AdGroupNewFrequencyConfigInput,
    AdGroupNewFrequencyConfigInputTypedDict,
)
from .adgroupnielsentrackingattributes import (
    AdGroupNielsenTrackingAttributes,
    AdGroupNielsenTrackingAttributesTypedDict,
)
from .adgroupnielsentrackingattributesinput import (
    AdGroupNielsenTrackingAttributesInput,
    AdGroupNielsenTrackingAttributesInputTypedDict,
)
from .adgrouproigoal import AdGroupRoiGoal, AdGroupRoiGoalTypedDict
from .adgrouproigoalinput import AdGroupRoiGoalInput, AdGroupRoiGoalInputTypedDict
from .adgroupworkflow import AdGroupWorkflow, AdGroupWorkflowTypedDict
from .allocationtype import AllocationType
from .apierror import APIError
from .budgetworkflow import BudgetWorkflow, BudgetWorkflowTypedDict
from .campaignchanneltype import CampaignChannelType
from .campaignconversionreportingcolumnworkflow import (
    CampaignConversionReportingColumnWorkflow,
    CampaignConversionReportingColumnWorkflowTypedDict,
)
from .campaigncreateroigoalworkflow import (
    CampaignCreateROIGoalWorkflow,
    CampaignCreateROIGoalWorkflowTypedDict,
)
from .campaigncreateworkflowadvancedinput import (
    CampaignCreateWorkflowAdvancedInput,
    CampaignCreateWorkflowAdvancedInputTypedDict,
)
from .campaigncreateworkflowinput import (
    CampaignCreateWorkflowInput,
    CampaignCreateWorkflowInputTypedDict,
)
from .campaigncreateworkflowprimaryinput import (
    CampaignCreateWorkflowPrimaryInput,
    CampaignCreateWorkflowPrimaryInputTypedDict,
)
from .campaigncreationadgroupinput import (
    CampaignCreationAdGroupInput,
    CampaignCreationAdGroupInputTypedDict,
)
from .campaignflightworkflow import (
    CampaignFlightWorkflow,
    CampaignFlightWorkflowTypedDict,
)
from .campaignflightworkflowinput import (
    CampaignFlightWorkflowInput,
    CampaignFlightWorkflowInputTypedDict,
)
from .campaignpacingmode import CampaignPacingMode
from .campaignpayload import CampaignPayload, CampaignPayloadTypedDict
from .campaignversionworkflow import (
    CampaignVersionWorkflow,
    CampaignVersionWorkflowTypedDict,
)
from .campaignworkflow import CampaignWorkflow, CampaignWorkflowTypedDict
from .contextualdatainput import ContextualDataInput, ContextualDataInputTypedDict
from .customcpatype import CustomCPAType
from .customroasconfig import CustomROASConfig, CustomROASConfigTypedDict
from .dimensionalbiddingdimensions import DimensionalBiddingDimensions
from .enhancednielsenreportingoptions import EnhancedNielsenReportingOptions
from .get_campaign_id_versionop import (
    GetCampaignIDVersionRequest,
    GetCampaignIDVersionRequestTypedDict,
)
from .graphqlqueryinput import (
    GraphQLQueryInput,
    GraphQLQueryInputTypedDict,
    Variables,
    VariablesTypedDict,
)
from .post_graphqlop import PostGraphqlResponse, PostGraphqlResponseTypedDict
from .problemdetails import ProblemDetails, ProblemDetailsTypedDict
from .problemdetails_error import ProblemDetailsError, ProblemDetailsErrorData
from .security import Security, SecurityTypedDict
from .seed import Seed, SeedTypedDict
from .seedcreationinput import SeedCreationInput, SeedCreationInputTypedDict
from .seedtargetingdatainput import (
    SeedTargetingDataInput,
    SeedTargetingDataInputTypedDict,
)
from .targetingendage import TargetingEndAge
from .targetinggender import TargetingGender
from .targetingstartage import TargetingStartAge
from .thirdpartydatainput import ThirdPartyDataInput, ThirdPartyDataInputTypedDict
from .usererror import UserError, UserErrorTypedDict


__all__ = [
    "APIError",
    "AdGroupAdvancedSettingsInput",
    "AdGroupAdvancedSettingsInputTypedDict",
    "AdGroupAssociateBidList",
    "AdGroupAssociateBidListInput",
    "AdGroupAssociateBidListInputTypedDict",
    "AdGroupAssociateBidListTypedDict",
    "AdGroupAudienceTargeting",
    "AdGroupAudienceTargetingInput",
    "AdGroupAudienceTargetingInputTypedDict",
    "AdGroupAudienceTargetingTypedDict",
    "AdGroupBudget",
    "AdGroupBudgetInput",
    "AdGroupBudgetInputTypedDict",
    "AdGroupBudgetTypedDict",
    "AdGroupChannel",
    "AdGroupComscoreSettings",
    "AdGroupComscoreSettingsInput",
    "AdGroupComscoreSettingsInputTypedDict",
    "AdGroupComscoreSettingsTypedDict",
    "AdGroupContractTargeting",
    "AdGroupContractTargetingInput",
    "AdGroupContractTargetingInputTypedDict",
    "AdGroupContractTargetingTypedDict",
    "AdGroupFlight",
    "AdGroupFlightInput",
    "AdGroupFlightInputTypedDict",
    "AdGroupFlightTypedDict",
    "AdGroupFunnelLocation",
    "AdGroupKoaOptimizationSettings",
    "AdGroupKoaOptimizationSettingsInput",
    "AdGroupKoaOptimizationSettingsInputTypedDict",
    "AdGroupKoaOptimizationSettingsTypedDict",
    "AdGroupNewFrequencyConfigInput",
    "AdGroupNewFrequencyConfigInputTypedDict",
    "AdGroupNielsenTrackingAttributes",
    "AdGroupNielsenTrackingAttributesInput",
    "AdGroupNielsenTrackingAttributesInputTypedDict",
    "AdGroupNielsenTrackingAttributesTypedDict",
    "AdGroupRoiGoal",
    "AdGroupRoiGoalInput",
    "AdGroupRoiGoalInputTypedDict",
    "AdGroupRoiGoalTypedDict",
    "AdGroupWorkflow",
    "AdGroupWorkflowTypedDict",
    "AllocationType",
    "BudgetWorkflow",
    "BudgetWorkflowTypedDict",
    "CampaignChannelType",
    "CampaignConversionReportingColumnWorkflow",
    "CampaignConversionReportingColumnWorkflowTypedDict",
    "CampaignCreateROIGoalWorkflow",
    "CampaignCreateROIGoalWorkflowTypedDict",
    "CampaignCreateWorkflowAdvancedInput",
    "CampaignCreateWorkflowAdvancedInputTypedDict",
    "CampaignCreateWorkflowInput",
    "CampaignCreateWorkflowInputTypedDict",
    "CampaignCreateWorkflowPrimaryInput",
    "CampaignCreateWorkflowPrimaryInputTypedDict",
    "CampaignCreationAdGroupInput",
    "CampaignCreationAdGroupInputTypedDict",
    "CampaignFlightWorkflow",
    "CampaignFlightWorkflowInput",
    "CampaignFlightWorkflowInputTypedDict",
    "CampaignFlightWorkflowTypedDict",
    "CampaignPacingMode",
    "CampaignPayload",
    "CampaignPayloadTypedDict",
    "CampaignVersionWorkflow",
    "CampaignVersionWorkflowTypedDict",
    "CampaignWorkflow",
    "CampaignWorkflowTypedDict",
    "ContextualDataInput",
    "ContextualDataInputTypedDict",
    "CustomCPAType",
    "CustomROASConfig",
    "CustomROASConfigTypedDict",
    "DimensionalBiddingDimensions",
    "EnhancedNielsenReportingOptions",
    "GetCampaignIDVersionRequest",
    "GetCampaignIDVersionRequestTypedDict",
    "GraphQLQueryInput",
    "GraphQLQueryInputTypedDict",
    "PostGraphqlResponse",
    "PostGraphqlResponseTypedDict",
    "ProblemDetails",
    "ProblemDetailsError",
    "ProblemDetailsErrorData",
    "ProblemDetailsTypedDict",
    "Security",
    "SecurityTypedDict",
    "Seed",
    "SeedCreationInput",
    "SeedCreationInputTypedDict",
    "SeedTargetingDataInput",
    "SeedTargetingDataInputTypedDict",
    "SeedTypedDict",
    "TargetingEndAge",
    "TargetingGender",
    "TargetingStartAge",
    "ThirdPartyDataInput",
    "ThirdPartyDataInputTypedDict",
    "UserError",
    "UserErrorTypedDict",
    "Variables",
    "VariablesTypedDict",
]
