"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .adgroupassociatebidlist import (
    AdGroupAssociateBidList,
    AdGroupAssociateBidListTypedDict,
)
from .adgroupassociatebidlistinput import (
    AdGroupAssociateBidListInput,
    AdGroupAssociateBidListInputTypedDict,
)
from .adgroupaudiencetargeting import (
    AdGroupAudienceTargeting,
    AdGroupAudienceTargetingTypedDict,
)
from .adgroupaudiencetargetinginput import (
    AdGroupAudienceTargetingInput,
    AdGroupAudienceTargetingInputTypedDict,
)
from .adgroupbudget import AdGroupBudget, AdGroupBudgetTypedDict
from .adgroupbudgetinput import AdGroupBudgetInput, AdGroupBudgetInputTypedDict
from .adgroupchannel import AdGroupChannel
from .adgroupcomscoresettings import (
    AdGroupComscoreSettings,
    AdGroupComscoreSettingsTypedDict,
)
from .adgroupcomscoresettingsinput import (
    AdGroupComscoreSettingsInput,
    AdGroupComscoreSettingsInputTypedDict,
)
from .adgroupcontracttargeting import (
    AdGroupContractTargeting,
    AdGroupContractTargetingTypedDict,
)
from .adgroupcontracttargetinginput import (
    AdGroupContractTargetingInput,
    AdGroupContractTargetingInputTypedDict,
)
from .adgroupcreateadgroupflightinput import (
    AdGroupCreateAdGroupFlightInput,
    AdGroupCreateAdGroupFlightInputTypedDict,
)
from .adgroupcreateadvancedsettingsinput import (
    AdGroupCreateAdvancedSettingsInput,
    AdGroupCreateAdvancedSettingsInputTypedDict,
)
from .adgroupcreateworkflowinput import (
    AdGroupCreateWorkflowInput,
    AdGroupCreateWorkflowInputTypedDict,
)
from .adgroupflight import AdGroupFlight, AdGroupFlightTypedDict
from .adgroupfunnellocation import AdGroupFunnelLocation
from .adgroupkoaoptimizationsettings import (
    AdGroupKoaOptimizationSettings,
    AdGroupKoaOptimizationSettingsTypedDict,
)
from .adgroupkoaoptimizationsettingsinput import (
    AdGroupKoaOptimizationSettingsInput,
    AdGroupKoaOptimizationSettingsInputTypedDict,
)
from .adgroupnewfrequencyconfiginput import (
    AdGroupNewFrequencyConfigInput,
    AdGroupNewFrequencyConfigInputTypedDict,
)
from .adgroupnielsentrackingattributes import (
    AdGroupNielsenTrackingAttributes,
    AdGroupNielsenTrackingAttributesTypedDict,
)
from .adgroupnielsentrackingattributesinput import (
    AdGroupNielsenTrackingAttributesInput,
    AdGroupNielsenTrackingAttributesInputTypedDict,
)
from .adgrouppayload import AdGroupPayload, AdGroupPayloadTypedDict
from .adgrouproigoal import AdGroupRoiGoal, AdGroupRoiGoalTypedDict
from .adgrouproigoalinput import AdGroupRoiGoalInput, AdGroupRoiGoalInputTypedDict
from .adgroupupdateadgroupflightinput import (
    AdGroupUpdateAdGroupFlightInput,
    AdGroupUpdateAdGroupFlightInputTypedDict,
)
from .adgroupupdateadvancedsettingsinput import (
    AdGroupUpdateAdvancedSettingsInput,
    AdGroupUpdateAdvancedSettingsInputTypedDict,
)
from .adgroupupdateaudiencetargetinginput import (
    AdGroupUpdateAudienceTargetingInput,
    AdGroupUpdateAudienceTargetingInputTypedDict,
)
from .adgroupupdatebudgetinput import (
    AdGroupUpdateBudgetInput,
    AdGroupUpdateBudgetInputTypedDict,
)
from .adgroupupdatecomscoresettingsinput import (
    AdGroupUpdateComscoreSettingsInput,
    AdGroupUpdateComscoreSettingsInputTypedDict,
)
from .adgroupupdatenielsentrackingattributesinput import (
    AdGroupUpdateNielsenTrackingAttributesInput,
    AdGroupUpdateNielsenTrackingAttributesInputTypedDict,
)
from .adgroupupdatenielsentrackingattributesinputworkflowsoptional import (
    AdGroupUpdateNielsenTrackingAttributesInputWorkflowsOptional,
    AdGroupUpdateNielsenTrackingAttributesInputWorkflowsOptionalTypedDict,
)
from .adgroupupdateworkflowinput import (
    AdGroupUpdateWorkflowInput,
    AdGroupUpdateWorkflowInputTypedDict,
)
from .adgroupworkflow import AdGroupWorkflow, AdGroupWorkflowTypedDict
from .allocationtype import AllocationType
from .apierror import APIError
from .budgetworkflow import BudgetWorkflow, BudgetWorkflowTypedDict
from .bulkjobstatusresponse import BulkJobStatusResponse, BulkJobStatusResponseTypedDict
from .bulkjobsubmitresponse import BulkJobSubmitResponse, BulkJobSubmitResponseTypedDict
from .campaignbulkpayload import CampaignBulkPayload, CampaignBulkPayloadTypedDict
from .campaignchanneltype import CampaignChannelType
from .campaignconversionreportingcolumnworkflow import (
    CampaignConversionReportingColumnWorkflow,
    CampaignConversionReportingColumnWorkflowTypedDict,
)
from .campaigncreateadgroupadvancedsettingsinput import (
    CampaignCreateAdGroupAdvancedSettingsInput,
    CampaignCreateAdGroupAdvancedSettingsInputTypedDict,
)
from .campaigncreateadgroupflightinput import (
    CampaignCreateAdGroupFlightInput,
    CampaignCreateAdGroupFlightInputTypedDict,
)
from .campaigncreateadgroupinput import (
    CampaignCreateAdGroupInput,
    CampaignCreateAdGroupInputTypedDict,
)
from .campaigncreateroigoalworkflow import (
    CampaignCreateROIGoalWorkflow,
    CampaignCreateROIGoalWorkflowTypedDict,
)
from .campaigncreateworkflowadvancedinput import (
    CampaignCreateWorkflowAdvancedInput,
    CampaignCreateWorkflowAdvancedInputTypedDict,
)
from .campaigncreateworkflowinput import (
    CampaignCreateWorkflowInput,
    CampaignCreateWorkflowInputTypedDict,
)
from .campaigncreateworkflowprimaryinput import (
    CampaignCreateWorkflowPrimaryInput,
    CampaignCreateWorkflowPrimaryInputTypedDict,
)
from .campaignflightworkflow import (
    CampaignFlightWorkflow,
    CampaignFlightWorkflowTypedDict,
)
from .campaignflightworkflowinput import (
    CampaignFlightWorkflowInput,
    CampaignFlightWorkflowInputTypedDict,
)
from .campaignpacingmode import CampaignPacingMode
from .campaignsinglepayload import CampaignSinglePayload, CampaignSinglePayloadTypedDict
from .campaignversionworkflow import (
    CampaignVersionWorkflow,
    CampaignVersionWorkflowTypedDict,
)
from .campaignworkflow import CampaignWorkflow, CampaignWorkflowTypedDict
from .customcpatype import CustomCPAType
from .customroasconfig import CustomROASConfig, CustomROASConfigTypedDict
from .decimalnullableworkflowsoptional import (
    DecimalNullableWorkflowsOptional,
    DecimalNullableWorkflowsOptionalTypedDict,
)
from .dimensionalbiddingdimensions import DimensionalBiddingDimensions
from .enhancednielsenreportingoptions import EnhancedNielsenReportingOptions
from .firstpartydatainput import FirstPartyDataInput, FirstPartyDataInputTypedDict
from .get_bulkjob_id_statusop import (
    GetBulkjobIDStatusRequest,
    GetBulkjobIDStatusRequestTypedDict,
)
from .get_campaign_id_versionop import (
    GetCampaignIDVersionRequest,
    GetCampaignIDVersionRequestTypedDict,
)
from .graphqlrequestinput import (
    GraphQLRequestInput,
    GraphQLRequestInputTypedDict,
    Variables,
    VariablesTypedDict,
)
from .int64nullableworkflowsoptional import (
    Int64NullableWorkflowsOptional,
    Int64NullableWorkflowsOptionalTypedDict,
)
from .post_adgroup_archiveop import (
    PostAdgroupArchiveRequest,
    PostAdgroupArchiveRequestTypedDict,
)
from .post_campaign_archiveop import (
    PostCampaignArchiveRequest,
    PostCampaignArchiveRequestTypedDict,
)
from .problemdetails import ProblemDetails, ProblemDetailsTypedDict
from .problemdetails_error import ProblemDetailsError, ProblemDetailsErrorData
from .security import Security, SecurityTypedDict
from .stringworkflowsoptional import (
    StringWorkflowsOptional,
    StringWorkflowsOptionalTypedDict,
)
from .targetingendage import TargetingEndAge
from .targetinggender import TargetingGender
from .targetingstartage import TargetingStartAge


__all__ = [
    "APIError",
    "AdGroupAssociateBidList",
    "AdGroupAssociateBidListInput",
    "AdGroupAssociateBidListInputTypedDict",
    "AdGroupAssociateBidListTypedDict",
    "AdGroupAudienceTargeting",
    "AdGroupAudienceTargetingInput",
    "AdGroupAudienceTargetingInputTypedDict",
    "AdGroupAudienceTargetingTypedDict",
    "AdGroupBudget",
    "AdGroupBudgetInput",
    "AdGroupBudgetInputTypedDict",
    "AdGroupBudgetTypedDict",
    "AdGroupChannel",
    "AdGroupComscoreSettings",
    "AdGroupComscoreSettingsInput",
    "AdGroupComscoreSettingsInputTypedDict",
    "AdGroupComscoreSettingsTypedDict",
    "AdGroupContractTargeting",
    "AdGroupContractTargetingInput",
    "AdGroupContractTargetingInputTypedDict",
    "AdGroupContractTargetingTypedDict",
    "AdGroupCreateAdGroupFlightInput",
    "AdGroupCreateAdGroupFlightInputTypedDict",
    "AdGroupCreateAdvancedSettingsInput",
    "AdGroupCreateAdvancedSettingsInputTypedDict",
    "AdGroupCreateWorkflowInput",
    "AdGroupCreateWorkflowInputTypedDict",
    "AdGroupFlight",
    "AdGroupFlightTypedDict",
    "AdGroupFunnelLocation",
    "AdGroupKoaOptimizationSettings",
    "AdGroupKoaOptimizationSettingsInput",
    "AdGroupKoaOptimizationSettingsInputTypedDict",
    "AdGroupKoaOptimizationSettingsTypedDict",
    "AdGroupNewFrequencyConfigInput",
    "AdGroupNewFrequencyConfigInputTypedDict",
    "AdGroupNielsenTrackingAttributes",
    "AdGroupNielsenTrackingAttributesInput",
    "AdGroupNielsenTrackingAttributesInputTypedDict",
    "AdGroupNielsenTrackingAttributesTypedDict",
    "AdGroupPayload",
    "AdGroupPayloadTypedDict",
    "AdGroupRoiGoal",
    "AdGroupRoiGoalInput",
    "AdGroupRoiGoalInputTypedDict",
    "AdGroupRoiGoalTypedDict",
    "AdGroupUpdateAdGroupFlightInput",
    "AdGroupUpdateAdGroupFlightInputTypedDict",
    "AdGroupUpdateAdvancedSettingsInput",
    "AdGroupUpdateAdvancedSettingsInputTypedDict",
    "AdGroupUpdateAudienceTargetingInput",
    "AdGroupUpdateAudienceTargetingInputTypedDict",
    "AdGroupUpdateBudgetInput",
    "AdGroupUpdateBudgetInputTypedDict",
    "AdGroupUpdateComscoreSettingsInput",
    "AdGroupUpdateComscoreSettingsInputTypedDict",
    "AdGroupUpdateNielsenTrackingAttributesInput",
    "AdGroupUpdateNielsenTrackingAttributesInputTypedDict",
    "AdGroupUpdateNielsenTrackingAttributesInputWorkflowsOptional",
    "AdGroupUpdateNielsenTrackingAttributesInputWorkflowsOptionalTypedDict",
    "AdGroupUpdateWorkflowInput",
    "AdGroupUpdateWorkflowInputTypedDict",
    "AdGroupWorkflow",
    "AdGroupWorkflowTypedDict",
    "AllocationType",
    "BudgetWorkflow",
    "BudgetWorkflowTypedDict",
    "BulkJobStatusResponse",
    "BulkJobStatusResponseTypedDict",
    "BulkJobSubmitResponse",
    "BulkJobSubmitResponseTypedDict",
    "CampaignBulkPayload",
    "CampaignBulkPayloadTypedDict",
    "CampaignChannelType",
    "CampaignConversionReportingColumnWorkflow",
    "CampaignConversionReportingColumnWorkflowTypedDict",
    "CampaignCreateAdGroupAdvancedSettingsInput",
    "CampaignCreateAdGroupAdvancedSettingsInputTypedDict",
    "CampaignCreateAdGroupFlightInput",
    "CampaignCreateAdGroupFlightInputTypedDict",
    "CampaignCreateAdGroupInput",
    "CampaignCreateAdGroupInputTypedDict",
    "CampaignCreateROIGoalWorkflow",
    "CampaignCreateROIGoalWorkflowTypedDict",
    "CampaignCreateWorkflowAdvancedInput",
    "CampaignCreateWorkflowAdvancedInputTypedDict",
    "CampaignCreateWorkflowInput",
    "CampaignCreateWorkflowInputTypedDict",
    "CampaignCreateWorkflowPrimaryInput",
    "CampaignCreateWorkflowPrimaryInputTypedDict",
    "CampaignFlightWorkflow",
    "CampaignFlightWorkflowInput",
    "CampaignFlightWorkflowInputTypedDict",
    "CampaignFlightWorkflowTypedDict",
    "CampaignPacingMode",
    "CampaignSinglePayload",
    "CampaignSinglePayloadTypedDict",
    "CampaignVersionWorkflow",
    "CampaignVersionWorkflowTypedDict",
    "CampaignWorkflow",
    "CampaignWorkflowTypedDict",
    "CustomCPAType",
    "CustomROASConfig",
    "CustomROASConfigTypedDict",
    "DecimalNullableWorkflowsOptional",
    "DecimalNullableWorkflowsOptionalTypedDict",
    "DimensionalBiddingDimensions",
    "EnhancedNielsenReportingOptions",
    "FirstPartyDataInput",
    "FirstPartyDataInputTypedDict",
    "GetBulkjobIDStatusRequest",
    "GetBulkjobIDStatusRequestTypedDict",
    "GetCampaignIDVersionRequest",
    "GetCampaignIDVersionRequestTypedDict",
    "GraphQLRequestInput",
    "GraphQLRequestInputTypedDict",
    "Int64NullableWorkflowsOptional",
    "Int64NullableWorkflowsOptionalTypedDict",
    "PostAdgroupArchiveRequest",
    "PostAdgroupArchiveRequestTypedDict",
    "PostCampaignArchiveRequest",
    "PostCampaignArchiveRequestTypedDict",
    "ProblemDetails",
    "ProblemDetailsError",
    "ProblemDetailsErrorData",
    "ProblemDetailsTypedDict",
    "Security",
    "SecurityTypedDict",
    "StringWorkflowsOptional",
    "StringWorkflowsOptionalTypedDict",
    "TargetingEndAge",
    "TargetingGender",
    "TargetingStartAge",
    "Variables",
    "VariablesTypedDict",
]
