"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module

if TYPE_CHECKING:
    from .adgroupassociatebidlist import (
        AdGroupAssociateBidList,
        AdGroupAssociateBidListTypedDict,
    )
    from .adgroupaudiencetargeting import (
        AdGroupAudienceTargeting,
        AdGroupAudienceTargetingTypedDict,
    )
    from .adgroupbudget import AdGroupBudget, AdGroupBudgetTypedDict
    from .adgroupbulkcreateworkflowinputwithvalidation import (
        AdGroupBulkCreateWorkflowInputWithValidation,
        AdGroupBulkCreateWorkflowInputWithValidationTypedDict,
    )
    from .adgroupbulkupdateworkflowinputwithvalidation import (
        AdGroupBulkUpdateWorkflowInputWithValidation,
        AdGroupBulkUpdateWorkflowInputWithValidationTypedDict,
    )
    from .adgroupchannel import AdGroupChannel
    from .adgroupcomscoresettings import (
        AdGroupComscoreSettings,
        AdGroupComscoreSettingsTypedDict,
    )
    from .adgroupcontracttargeting import (
        AdGroupContractTargeting,
        AdGroupContractTargetingTypedDict,
    )
    from .adgroupcreateworkflowinput import (
        AdGroupCreateWorkflowInput,
        AdGroupCreateWorkflowInputTypedDict,
    )
    from .adgroupcreateworkflowinputwithvalidation import (
        AdGroupCreateWorkflowInputWithValidation,
        AdGroupCreateWorkflowInputWithValidationTypedDict,
    )
    from .adgroupcreateworkflowprimaryinput import (
        AdGroupCreateWorkflowPrimaryInput,
        AdGroupCreateWorkflowPrimaryInputTypedDict,
    )
    from .adgroupflight import AdGroupFlight, AdGroupFlightTypedDict
    from .adgroupfunnellocation import AdGroupFunnelLocation
    from .adgroupkoaoptimizationsettings import (
        AdGroupKoaOptimizationSettings,
        AdGroupKoaOptimizationSettingsTypedDict,
    )
    from .adgroupnielsentrackingattributes import (
        AdGroupNielsenTrackingAttributes,
        AdGroupNielsenTrackingAttributesTypedDict,
    )
    from .adgrouppayload import AdGroupPayload, AdGroupPayloadTypedDict
    from .adgrouproigoal import AdGroupROIGoal, AdGroupROIGoalTypedDict
    from .adgroupupdateworkflowinput import (
        AdGroupUpdateWorkflowInput,
        AdGroupUpdateWorkflowInputTypedDict,
    )
    from .adgroupupdateworkflowinputwithvalidation import (
        AdGroupUpdateWorkflowInputWithValidation,
        AdGroupUpdateWorkflowInputWithValidationTypedDict,
    )
    from .adgroupupdateworkflowprimaryinput import (
        AdGroupUpdateWorkflowPrimaryInput,
        AdGroupUpdateWorkflowPrimaryInputTypedDict,
    )
    from .adgroupworkflow import AdGroupWorkflow, AdGroupWorkflowTypedDict
    from .adgroupworkflowadvancedinput import (
        AdGroupWorkflowAdvancedInput,
        AdGroupWorkflowAdvancedInputTypedDict,
    )
    from .adgroupworkflowassociatebidlistinput import (
        AdGroupWorkflowAssociateBidListInput,
        AdGroupWorkflowAssociateBidListInputTypedDict,
    )
    from .adgroupworkflowaudiencetargetinginput import (
        AdGroupWorkflowAudienceTargetingInput,
        AdGroupWorkflowAudienceTargetingInputTypedDict,
    )
    from .adgroupworkflowbudgetinput import (
        AdGroupWorkflowBudgetInput,
        AdGroupWorkflowBudgetInputTypedDict,
    )
    from .adgroupworkflowcomscoresettingsinput import (
        AdGroupWorkflowComscoreSettingsInput,
        AdGroupWorkflowComscoreSettingsInputTypedDict,
    )
    from .adgroupworkflowcontracttargetinginput import (
        AdGroupWorkflowContractTargetingInput,
        AdGroupWorkflowContractTargetingInputTypedDict,
    )
    from .adgroupworkflowflightinput import (
        AdGroupWorkflowFlightInput,
        AdGroupWorkflowFlightInputTypedDict,
    )
    from .adgroupworkflowkoaoptimizationsettingsinput import (
        AdGroupWorkflowKoaOptimizationSettingsInput,
        AdGroupWorkflowKoaOptimizationSettingsInputTypedDict,
    )
    from .adgroupworkflownewfrequencyconfiginput import (
        AdGroupWorkflowNewFrequencyConfigInput,
        AdGroupWorkflowNewFrequencyConfigInputTypedDict,
    )
    from .adgroupworkflownielsentrackingattributesinput import (
        AdGroupWorkflowNielsenTrackingAttributesInput,
        AdGroupWorkflowNielsenTrackingAttributesInputTypedDict,
    )
    from .adgroupworkflowroigoalinput import (
        AdGroupWorkflowROIGoalInput,
        AdGroupWorkflowROIGoalInputTypedDict,
    )
    from .allocationtype import AllocationType
    from .apierror import APIError
    from .bulkjobstatusresponse import (
        BulkJobStatusResponse,
        BulkJobStatusResponseTypedDict,
    )
    from .bulkjobsubmitresponse import (
        BulkJobSubmitResponse,
        BulkJobSubmitResponseTypedDict,
    )
    from .callpubapiworkflowinput import (
        CallPubAPIWorkflowInput,
        CallPubAPIWorkflowInputTypedDict,
    )
    from .campaignbulkcreateworkflowinputwithvalidation import (
        CampaignBulkCreateWorkflowInputWithValidation,
        CampaignBulkCreateWorkflowInputWithValidationTypedDict,
    )
    from .campaignbulkupdateworkflowinputwithvalidation import (
        CampaignBulkUpdateWorkflowInputWithValidation,
        CampaignBulkUpdateWorkflowInputWithValidationTypedDict,
    )
    from .campaignchanneltype import CampaignChannelType
    from .campaigncreateworkflowadgroupadvancedinput import (
        CampaignCreateWorkflowAdGroupAdvancedInput,
        CampaignCreateWorkflowAdGroupAdvancedInputTypedDict,
    )
    from .campaigncreateworkflowadgroupflightinput import (
        CampaignCreateWorkflowAdGroupFlightInput,
        CampaignCreateWorkflowAdGroupFlightInputTypedDict,
    )
    from .campaigncreateworkflowadgroupinput import (
        CampaignCreateWorkflowAdGroupInput,
        CampaignCreateWorkflowAdGroupInputTypedDict,
    )
    from .campaigncreateworkflowinput import (
        CampaignCreateWorkflowInput,
        CampaignCreateWorkflowInputTypedDict,
    )
    from .campaigncreateworkflowinputwithvalidation import (
        CampaignCreateWorkflowInputWithValidation,
        CampaignCreateWorkflowInputWithValidationTypedDict,
    )
    from .campaigncreateworkflowprimaryinput import (
        CampaignCreateWorkflowPrimaryInput,
        CampaignCreateWorkflowPrimaryInputTypedDict,
    )
    from .campaignflightworkflow import (
        CampaignFlightWorkflow,
        CampaignFlightWorkflowTypedDict,
    )
    from .campaignpacingmode import CampaignPacingMode
    from .campaignpayload import CampaignPayload, CampaignPayloadTypedDict
    from .campaignupdateworkflowinput import (
        CampaignUpdateWorkflowInput,
        CampaignUpdateWorkflowInputTypedDict,
    )
    from .campaignupdateworkflowinputwithvalidation import (
        CampaignUpdateWorkflowInputWithValidation,
        CampaignUpdateWorkflowInputWithValidationTypedDict,
    )
    from .campaignupdateworkflowprimaryinput import (
        CampaignUpdateWorkflowPrimaryInput,
        CampaignUpdateWorkflowPrimaryInputTypedDict,
    )
    from .campaignversionworkflow import (
        CampaignVersionWorkflow,
        CampaignVersionWorkflowTypedDict,
    )
    from .campaignworkflow import CampaignWorkflow, CampaignWorkflowTypedDict
    from .campaignworkflowadvancedinput import (
        CampaignWorkflowAdvancedInput,
        CampaignWorkflowAdvancedInputTypedDict,
    )
    from .campaignworkflowbudgetinput import (
        CampaignWorkflowBudgetInput,
        CampaignWorkflowBudgetInputTypedDict,
    )
    from .campaignworkflowcampaignconversionreportingcolumninput import (
        CampaignWorkflowCampaignConversionReportingColumnInput,
        CampaignWorkflowCampaignConversionReportingColumnInputTypedDict,
    )
    from .campaignworkflowflightinput import (
        CampaignWorkflowFlightInput,
        CampaignWorkflowFlightInputTypedDict,
    )
    from .campaignworkflowroigoalinput import (
        CampaignWorkflowROIGoalInput,
        CampaignWorkflowROIGoalInputTypedDict,
    )
    from .customcpatype import CustomCPAType
    from .customroasconfig import CustomROASConfig, CustomROASConfigTypedDict
    from .dimensionalbiddingdimensions import DimensionalBiddingDimensions
    from .enhancednielsenreportingoptions import EnhancedNielsenReportingOptions
    from .firstpartydatainput import FirstPartyDataInput, FirstPartyDataInputTypedDict
    from .get_bulkjob_id_statusop import (
        GetBulkjobIDStatusRequest,
        GetBulkjobIDStatusRequestTypedDict,
    )
    from .get_campaign_id_versionop import (
        GetCampaignIDVersionRequest,
        GetCampaignIDVersionRequestTypedDict,
    )
    from .graphqlrequestinput import (
        GraphQLRequestInput,
        GraphQLRequestInputTypedDict,
        Variables,
        VariablesTypedDict,
    )
    from .post_adgroup_archiveop import (
        PostAdgroupArchiveRequest,
        PostAdgroupArchiveRequestTypedDict,
    )
    from .post_campaign_archiveop import (
        PostCampaignArchiveRequest,
        PostCampaignArchiveRequestTypedDict,
    )
    from .post_pubapiop import PostPubapiResponse, PostPubapiResponseTypedDict
    from .problemdetails import ProblemDetails, ProblemDetailsTypedDict
    from .problemdetails_error import ProblemDetailsError, ProblemDetailsErrorData
    from .pubapimethodtype import PubAPIMethodType
    from .security import Security, SecurityTypedDict
    from .targetingendage import TargetingEndAge
    from .targetinggender import TargetingGender
    from .targetingstartage import TargetingStartAge
    from .workflowstatus import WorkflowStatus

__all__ = [
    "APIError",
    "AdGroupAssociateBidList",
    "AdGroupAssociateBidListTypedDict",
    "AdGroupAudienceTargeting",
    "AdGroupAudienceTargetingTypedDict",
    "AdGroupBudget",
    "AdGroupBudgetTypedDict",
    "AdGroupBulkCreateWorkflowInputWithValidation",
    "AdGroupBulkCreateWorkflowInputWithValidationTypedDict",
    "AdGroupBulkUpdateWorkflowInputWithValidation",
    "AdGroupBulkUpdateWorkflowInputWithValidationTypedDict",
    "AdGroupChannel",
    "AdGroupComscoreSettings",
    "AdGroupComscoreSettingsTypedDict",
    "AdGroupContractTargeting",
    "AdGroupContractTargetingTypedDict",
    "AdGroupCreateWorkflowInput",
    "AdGroupCreateWorkflowInputTypedDict",
    "AdGroupCreateWorkflowInputWithValidation",
    "AdGroupCreateWorkflowInputWithValidationTypedDict",
    "AdGroupCreateWorkflowPrimaryInput",
    "AdGroupCreateWorkflowPrimaryInputTypedDict",
    "AdGroupFlight",
    "AdGroupFlightTypedDict",
    "AdGroupFunnelLocation",
    "AdGroupKoaOptimizationSettings",
    "AdGroupKoaOptimizationSettingsTypedDict",
    "AdGroupNielsenTrackingAttributes",
    "AdGroupNielsenTrackingAttributesTypedDict",
    "AdGroupPayload",
    "AdGroupPayloadTypedDict",
    "AdGroupROIGoal",
    "AdGroupROIGoalTypedDict",
    "AdGroupUpdateWorkflowInput",
    "AdGroupUpdateWorkflowInputTypedDict",
    "AdGroupUpdateWorkflowInputWithValidation",
    "AdGroupUpdateWorkflowInputWithValidationTypedDict",
    "AdGroupUpdateWorkflowPrimaryInput",
    "AdGroupUpdateWorkflowPrimaryInputTypedDict",
    "AdGroupWorkflow",
    "AdGroupWorkflowAdvancedInput",
    "AdGroupWorkflowAdvancedInputTypedDict",
    "AdGroupWorkflowAssociateBidListInput",
    "AdGroupWorkflowAssociateBidListInputTypedDict",
    "AdGroupWorkflowAudienceTargetingInput",
    "AdGroupWorkflowAudienceTargetingInputTypedDict",
    "AdGroupWorkflowBudgetInput",
    "AdGroupWorkflowBudgetInputTypedDict",
    "AdGroupWorkflowComscoreSettingsInput",
    "AdGroupWorkflowComscoreSettingsInputTypedDict",
    "AdGroupWorkflowContractTargetingInput",
    "AdGroupWorkflowContractTargetingInputTypedDict",
    "AdGroupWorkflowFlightInput",
    "AdGroupWorkflowFlightInputTypedDict",
    "AdGroupWorkflowKoaOptimizationSettingsInput",
    "AdGroupWorkflowKoaOptimizationSettingsInputTypedDict",
    "AdGroupWorkflowNewFrequencyConfigInput",
    "AdGroupWorkflowNewFrequencyConfigInputTypedDict",
    "AdGroupWorkflowNielsenTrackingAttributesInput",
    "AdGroupWorkflowNielsenTrackingAttributesInputTypedDict",
    "AdGroupWorkflowROIGoalInput",
    "AdGroupWorkflowROIGoalInputTypedDict",
    "AdGroupWorkflowTypedDict",
    "AllocationType",
    "BulkJobStatusResponse",
    "BulkJobStatusResponseTypedDict",
    "BulkJobSubmitResponse",
    "BulkJobSubmitResponseTypedDict",
    "CallPubAPIWorkflowInput",
    "CallPubAPIWorkflowInputTypedDict",
    "CampaignBulkCreateWorkflowInputWithValidation",
    "CampaignBulkCreateWorkflowInputWithValidationTypedDict",
    "CampaignBulkUpdateWorkflowInputWithValidation",
    "CampaignBulkUpdateWorkflowInputWithValidationTypedDict",
    "CampaignChannelType",
    "CampaignCreateWorkflowAdGroupAdvancedInput",
    "CampaignCreateWorkflowAdGroupAdvancedInputTypedDict",
    "CampaignCreateWorkflowAdGroupFlightInput",
    "CampaignCreateWorkflowAdGroupFlightInputTypedDict",
    "CampaignCreateWorkflowAdGroupInput",
    "CampaignCreateWorkflowAdGroupInputTypedDict",
    "CampaignCreateWorkflowInput",
    "CampaignCreateWorkflowInputTypedDict",
    "CampaignCreateWorkflowInputWithValidation",
    "CampaignCreateWorkflowInputWithValidationTypedDict",
    "CampaignCreateWorkflowPrimaryInput",
    "CampaignCreateWorkflowPrimaryInputTypedDict",
    "CampaignFlightWorkflow",
    "CampaignFlightWorkflowTypedDict",
    "CampaignPacingMode",
    "CampaignPayload",
    "CampaignPayloadTypedDict",
    "CampaignUpdateWorkflowInput",
    "CampaignUpdateWorkflowInputTypedDict",
    "CampaignUpdateWorkflowInputWithValidation",
    "CampaignUpdateWorkflowInputWithValidationTypedDict",
    "CampaignUpdateWorkflowPrimaryInput",
    "CampaignUpdateWorkflowPrimaryInputTypedDict",
    "CampaignVersionWorkflow",
    "CampaignVersionWorkflowTypedDict",
    "CampaignWorkflow",
    "CampaignWorkflowAdvancedInput",
    "CampaignWorkflowAdvancedInputTypedDict",
    "CampaignWorkflowBudgetInput",
    "CampaignWorkflowBudgetInputTypedDict",
    "CampaignWorkflowCampaignConversionReportingColumnInput",
    "CampaignWorkflowCampaignConversionReportingColumnInputTypedDict",
    "CampaignWorkflowFlightInput",
    "CampaignWorkflowFlightInputTypedDict",
    "CampaignWorkflowROIGoalInput",
    "CampaignWorkflowROIGoalInputTypedDict",
    "CampaignWorkflowTypedDict",
    "CustomCPAType",
    "CustomROASConfig",
    "CustomROASConfigTypedDict",
    "DimensionalBiddingDimensions",
    "EnhancedNielsenReportingOptions",
    "FirstPartyDataInput",
    "FirstPartyDataInputTypedDict",
    "GetBulkjobIDStatusRequest",
    "GetBulkjobIDStatusRequestTypedDict",
    "GetCampaignIDVersionRequest",
    "GetCampaignIDVersionRequestTypedDict",
    "GraphQLRequestInput",
    "GraphQLRequestInputTypedDict",
    "PostAdgroupArchiveRequest",
    "PostAdgroupArchiveRequestTypedDict",
    "PostCampaignArchiveRequest",
    "PostCampaignArchiveRequestTypedDict",
    "PostPubapiResponse",
    "PostPubapiResponseTypedDict",
    "ProblemDetails",
    "ProblemDetailsError",
    "ProblemDetailsErrorData",
    "ProblemDetailsTypedDict",
    "PubAPIMethodType",
    "Security",
    "SecurityTypedDict",
    "TargetingEndAge",
    "TargetingGender",
    "TargetingStartAge",
    "Variables",
    "VariablesTypedDict",
    "WorkflowStatus",
]

_dynamic_imports: dict[str, str] = {
    "AdGroupAssociateBidList": ".adgroupassociatebidlist",
    "AdGroupAssociateBidListTypedDict": ".adgroupassociatebidlist",
    "AdGroupAudienceTargeting": ".adgroupaudiencetargeting",
    "AdGroupAudienceTargetingTypedDict": ".adgroupaudiencetargeting",
    "AdGroupBudget": ".adgroupbudget",
    "AdGroupBudgetTypedDict": ".adgroupbudget",
    "AdGroupBulkCreateWorkflowInputWithValidation": ".adgroupbulkcreateworkflowinputwithvalidation",
    "AdGroupBulkCreateWorkflowInputWithValidationTypedDict": ".adgroupbulkcreateworkflowinputwithvalidation",
    "AdGroupBulkUpdateWorkflowInputWithValidation": ".adgroupbulkupdateworkflowinputwithvalidation",
    "AdGroupBulkUpdateWorkflowInputWithValidationTypedDict": ".adgroupbulkupdateworkflowinputwithvalidation",
    "AdGroupChannel": ".adgroupchannel",
    "AdGroupComscoreSettings": ".adgroupcomscoresettings",
    "AdGroupComscoreSettingsTypedDict": ".adgroupcomscoresettings",
    "AdGroupContractTargeting": ".adgroupcontracttargeting",
    "AdGroupContractTargetingTypedDict": ".adgroupcontracttargeting",
    "AdGroupCreateWorkflowInput": ".adgroupcreateworkflowinput",
    "AdGroupCreateWorkflowInputTypedDict": ".adgroupcreateworkflowinput",
    "AdGroupCreateWorkflowInputWithValidation": ".adgroupcreateworkflowinputwithvalidation",
    "AdGroupCreateWorkflowInputWithValidationTypedDict": ".adgroupcreateworkflowinputwithvalidation",
    "AdGroupCreateWorkflowPrimaryInput": ".adgroupcreateworkflowprimaryinput",
    "AdGroupCreateWorkflowPrimaryInputTypedDict": ".adgroupcreateworkflowprimaryinput",
    "AdGroupFlight": ".adgroupflight",
    "AdGroupFlightTypedDict": ".adgroupflight",
    "AdGroupFunnelLocation": ".adgroupfunnellocation",
    "AdGroupKoaOptimizationSettings": ".adgroupkoaoptimizationsettings",
    "AdGroupKoaOptimizationSettingsTypedDict": ".adgroupkoaoptimizationsettings",
    "AdGroupNielsenTrackingAttributes": ".adgroupnielsentrackingattributes",
    "AdGroupNielsenTrackingAttributesTypedDict": ".adgroupnielsentrackingattributes",
    "AdGroupPayload": ".adgrouppayload",
    "AdGroupPayloadTypedDict": ".adgrouppayload",
    "AdGroupROIGoal": ".adgrouproigoal",
    "AdGroupROIGoalTypedDict": ".adgrouproigoal",
    "AdGroupUpdateWorkflowInput": ".adgroupupdateworkflowinput",
    "AdGroupUpdateWorkflowInputTypedDict": ".adgroupupdateworkflowinput",
    "AdGroupUpdateWorkflowInputWithValidation": ".adgroupupdateworkflowinputwithvalidation",
    "AdGroupUpdateWorkflowInputWithValidationTypedDict": ".adgroupupdateworkflowinputwithvalidation",
    "AdGroupUpdateWorkflowPrimaryInput": ".adgroupupdateworkflowprimaryinput",
    "AdGroupUpdateWorkflowPrimaryInputTypedDict": ".adgroupupdateworkflowprimaryinput",
    "AdGroupWorkflow": ".adgroupworkflow",
    "AdGroupWorkflowTypedDict": ".adgroupworkflow",
    "AdGroupWorkflowAdvancedInput": ".adgroupworkflowadvancedinput",
    "AdGroupWorkflowAdvancedInputTypedDict": ".adgroupworkflowadvancedinput",
    "AdGroupWorkflowAssociateBidListInput": ".adgroupworkflowassociatebidlistinput",
    "AdGroupWorkflowAssociateBidListInputTypedDict": ".adgroupworkflowassociatebidlistinput",
    "AdGroupWorkflowAudienceTargetingInput": ".adgroupworkflowaudiencetargetinginput",
    "AdGroupWorkflowAudienceTargetingInputTypedDict": ".adgroupworkflowaudiencetargetinginput",
    "AdGroupWorkflowBudgetInput": ".adgroupworkflowbudgetinput",
    "AdGroupWorkflowBudgetInputTypedDict": ".adgroupworkflowbudgetinput",
    "AdGroupWorkflowComscoreSettingsInput": ".adgroupworkflowcomscoresettingsinput",
    "AdGroupWorkflowComscoreSettingsInputTypedDict": ".adgroupworkflowcomscoresettingsinput",
    "AdGroupWorkflowContractTargetingInput": ".adgroupworkflowcontracttargetinginput",
    "AdGroupWorkflowContractTargetingInputTypedDict": ".adgroupworkflowcontracttargetinginput",
    "AdGroupWorkflowFlightInput": ".adgroupworkflowflightinput",
    "AdGroupWorkflowFlightInputTypedDict": ".adgroupworkflowflightinput",
    "AdGroupWorkflowKoaOptimizationSettingsInput": ".adgroupworkflowkoaoptimizationsettingsinput",
    "AdGroupWorkflowKoaOptimizationSettingsInputTypedDict": ".adgroupworkflowkoaoptimizationsettingsinput",
    "AdGroupWorkflowNewFrequencyConfigInput": ".adgroupworkflownewfrequencyconfiginput",
    "AdGroupWorkflowNewFrequencyConfigInputTypedDict": ".adgroupworkflownewfrequencyconfiginput",
    "AdGroupWorkflowNielsenTrackingAttributesInput": ".adgroupworkflownielsentrackingattributesinput",
    "AdGroupWorkflowNielsenTrackingAttributesInputTypedDict": ".adgroupworkflownielsentrackingattributesinput",
    "AdGroupWorkflowROIGoalInput": ".adgroupworkflowroigoalinput",
    "AdGroupWorkflowROIGoalInputTypedDict": ".adgroupworkflowroigoalinput",
    "AllocationType": ".allocationtype",
    "APIError": ".apierror",
    "BulkJobStatusResponse": ".bulkjobstatusresponse",
    "BulkJobStatusResponseTypedDict": ".bulkjobstatusresponse",
    "BulkJobSubmitResponse": ".bulkjobsubmitresponse",
    "BulkJobSubmitResponseTypedDict": ".bulkjobsubmitresponse",
    "CallPubAPIWorkflowInput": ".callpubapiworkflowinput",
    "CallPubAPIWorkflowInputTypedDict": ".callpubapiworkflowinput",
    "CampaignBulkCreateWorkflowInputWithValidation": ".campaignbulkcreateworkflowinputwithvalidation",
    "CampaignBulkCreateWorkflowInputWithValidationTypedDict": ".campaignbulkcreateworkflowinputwithvalidation",
    "CampaignBulkUpdateWorkflowInputWithValidation": ".campaignbulkupdateworkflowinputwithvalidation",
    "CampaignBulkUpdateWorkflowInputWithValidationTypedDict": ".campaignbulkupdateworkflowinputwithvalidation",
    "CampaignChannelType": ".campaignchanneltype",
    "CampaignCreateWorkflowAdGroupAdvancedInput": ".campaigncreateworkflowadgroupadvancedinput",
    "CampaignCreateWorkflowAdGroupAdvancedInputTypedDict": ".campaigncreateworkflowadgroupadvancedinput",
    "CampaignCreateWorkflowAdGroupFlightInput": ".campaigncreateworkflowadgroupflightinput",
    "CampaignCreateWorkflowAdGroupFlightInputTypedDict": ".campaigncreateworkflowadgroupflightinput",
    "CampaignCreateWorkflowAdGroupInput": ".campaigncreateworkflowadgroupinput",
    "CampaignCreateWorkflowAdGroupInputTypedDict": ".campaigncreateworkflowadgroupinput",
    "CampaignCreateWorkflowInput": ".campaigncreateworkflowinput",
    "CampaignCreateWorkflowInputTypedDict": ".campaigncreateworkflowinput",
    "CampaignCreateWorkflowInputWithValidation": ".campaigncreateworkflowinputwithvalidation",
    "CampaignCreateWorkflowInputWithValidationTypedDict": ".campaigncreateworkflowinputwithvalidation",
    "CampaignCreateWorkflowPrimaryInput": ".campaigncreateworkflowprimaryinput",
    "CampaignCreateWorkflowPrimaryInputTypedDict": ".campaigncreateworkflowprimaryinput",
    "CampaignFlightWorkflow": ".campaignflightworkflow",
    "CampaignFlightWorkflowTypedDict": ".campaignflightworkflow",
    "CampaignPacingMode": ".campaignpacingmode",
    "CampaignPayload": ".campaignpayload",
    "CampaignPayloadTypedDict": ".campaignpayload",
    "CampaignUpdateWorkflowInput": ".campaignupdateworkflowinput",
    "CampaignUpdateWorkflowInputTypedDict": ".campaignupdateworkflowinput",
    "CampaignUpdateWorkflowInputWithValidation": ".campaignupdateworkflowinputwithvalidation",
    "CampaignUpdateWorkflowInputWithValidationTypedDict": ".campaignupdateworkflowinputwithvalidation",
    "CampaignUpdateWorkflowPrimaryInput": ".campaignupdateworkflowprimaryinput",
    "CampaignUpdateWorkflowPrimaryInputTypedDict": ".campaignupdateworkflowprimaryinput",
    "CampaignVersionWorkflow": ".campaignversionworkflow",
    "CampaignVersionWorkflowTypedDict": ".campaignversionworkflow",
    "CampaignWorkflow": ".campaignworkflow",
    "CampaignWorkflowTypedDict": ".campaignworkflow",
    "CampaignWorkflowAdvancedInput": ".campaignworkflowadvancedinput",
    "CampaignWorkflowAdvancedInputTypedDict": ".campaignworkflowadvancedinput",
    "CampaignWorkflowBudgetInput": ".campaignworkflowbudgetinput",
    "CampaignWorkflowBudgetInputTypedDict": ".campaignworkflowbudgetinput",
    "CampaignWorkflowCampaignConversionReportingColumnInput": ".campaignworkflowcampaignconversionreportingcolumninput",
    "CampaignWorkflowCampaignConversionReportingColumnInputTypedDict": ".campaignworkflowcampaignconversionreportingcolumninput",
    "CampaignWorkflowFlightInput": ".campaignworkflowflightinput",
    "CampaignWorkflowFlightInputTypedDict": ".campaignworkflowflightinput",
    "CampaignWorkflowROIGoalInput": ".campaignworkflowroigoalinput",
    "CampaignWorkflowROIGoalInputTypedDict": ".campaignworkflowroigoalinput",
    "CustomCPAType": ".customcpatype",
    "CustomROASConfig": ".customroasconfig",
    "CustomROASConfigTypedDict": ".customroasconfig",
    "DimensionalBiddingDimensions": ".dimensionalbiddingdimensions",
    "EnhancedNielsenReportingOptions": ".enhancednielsenreportingoptions",
    "FirstPartyDataInput": ".firstpartydatainput",
    "FirstPartyDataInputTypedDict": ".firstpartydatainput",
    "GetBulkjobIDStatusRequest": ".get_bulkjob_id_statusop",
    "GetBulkjobIDStatusRequestTypedDict": ".get_bulkjob_id_statusop",
    "GetCampaignIDVersionRequest": ".get_campaign_id_versionop",
    "GetCampaignIDVersionRequestTypedDict": ".get_campaign_id_versionop",
    "GraphQLRequestInput": ".graphqlrequestinput",
    "GraphQLRequestInputTypedDict": ".graphqlrequestinput",
    "Variables": ".graphqlrequestinput",
    "VariablesTypedDict": ".graphqlrequestinput",
    "PostAdgroupArchiveRequest": ".post_adgroup_archiveop",
    "PostAdgroupArchiveRequestTypedDict": ".post_adgroup_archiveop",
    "PostCampaignArchiveRequest": ".post_campaign_archiveop",
    "PostCampaignArchiveRequestTypedDict": ".post_campaign_archiveop",
    "PostPubapiResponse": ".post_pubapiop",
    "PostPubapiResponseTypedDict": ".post_pubapiop",
    "ProblemDetails": ".problemdetails",
    "ProblemDetailsTypedDict": ".problemdetails",
    "ProblemDetailsError": ".problemdetails_error",
    "ProblemDetailsErrorData": ".problemdetails_error",
    "PubAPIMethodType": ".pubapimethodtype",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "TargetingEndAge": ".targetingendage",
    "TargetingGender": ".targetinggender",
    "TargetingStartAge": ".targetingstartage",
    "WorkflowStatus": ".workflowstatus",
}


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = import_module(module_name, __package__)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)
