"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupComscoreSettingsTypedDict(TypedDict):
    is_enabled: bool
    demographic_member_ids: Nullable[List[int]]
    mobile_demographic_member_ids: Nullable[List[int]]
    population_id: NotRequired[Nullable[int]]


class AdGroupComscoreSettings(BaseModel):
    is_enabled: Annotated[bool, pydantic.Field(alias="isEnabled")]

    demographic_member_ids: Annotated[
        Nullable[List[int]], pydantic.Field(alias="demographicMemberIds")
    ]

    mobile_demographic_member_ids: Annotated[
        Nullable[List[int]], pydantic.Field(alias="mobileDemographicMemberIds")
    ]

    population_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="populationId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["populationId"]
        nullable_fields = [
            "populationId",
            "demographicMemberIds",
            "mobileDemographicMemberIds",
        ]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
