"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupWorkflowKoaOptimizationSettingsInputTypedDict(TypedDict):
    are_future_koa_features_enabled: NotRequired[Nullable[bool]]
    predictive_clearing_enabled: NotRequired[Nullable[bool]]


class AdGroupWorkflowKoaOptimizationSettingsInput(BaseModel):
    are_future_koa_features_enabled: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="areFutureKoaFeaturesEnabled")
    ] = UNSET

    predictive_clearing_enabled: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="predictiveClearingEnabled")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["areFutureKoaFeaturesEnabled", "predictiveClearingEnabled"]
        )
        nullable_fields = set(
            ["areFutureKoaFeaturesEnabled", "predictiveClearingEnabled"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdGroupWorkflowKoaOptimizationSettingsInput.model_rebuild()
except NameError:
    pass
