"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, Nullable, UNSET_SENTINEL
from typing_extensions import Annotated, TypedDict


class AdGroupOwnedBidListTypedDict(TypedDict):
    bid_list_id: Nullable[str]


class AdGroupOwnedBidList(BaseModel):
    bid_list_id: Annotated[Nullable[str], pydantic.Field(alias="bidListId")]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    AdGroupOwnedBidList.model_rebuild()
except NameError:
    pass
