"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, Nullable, UNSET_SENTINEL
from typing_extensions import Annotated, TypedDict


class AdGroupAssociateBidListTypedDict(TypedDict):
    bid_list_id: Nullable[str]
    is_enabled: bool
    is_default_for_dimension: bool


class AdGroupAssociateBidList(BaseModel):
    bid_list_id: Annotated[Nullable[str], pydantic.Field(alias="bidListId")]

    is_enabled: Annotated[bool, pydantic.Field(alias="isEnabled")]

    is_default_for_dimension: Annotated[
        bool, pydantic.Field(alias="isDefaultForDimension")
    ]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    AdGroupAssociateBidList.model_rebuild()
except NameError:
    pass
