"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgroupupdatenielsentrackingattributesinput import (
    AdGroupUpdateNielsenTrackingAttributesInput,
    AdGroupUpdateNielsenTrackingAttributesInputTypedDict,
)
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AdGroupUpdateNielsenTrackingAttributesInputWorkflowsOptionalTypedDict(TypedDict):
    value: NotRequired[AdGroupUpdateNielsenTrackingAttributesInputTypedDict]


class AdGroupUpdateNielsenTrackingAttributesInputWorkflowsOptional(BaseModel):
    value: Optional[AdGroupUpdateNielsenTrackingAttributesInput] = None
