"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgroupcreateworkflowprimaryinput import (
    AdGroupCreateWorkflowPrimaryInput,
    AdGroupCreateWorkflowPrimaryInputTypedDict,
)
from .adgroupworkflowadvancedinput import (
    AdGroupWorkflowAdvancedInput,
    AdGroupWorkflowAdvancedInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, Nullable, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupCreateWorkflowInputTypedDict(TypedDict):
    primary_input: AdGroupCreateWorkflowPrimaryInputTypedDict
    campaign_id: Nullable[str]
    advanced_input: NotRequired[AdGroupWorkflowAdvancedInputTypedDict]


class AdGroupCreateWorkflowInput(BaseModel):
    primary_input: Annotated[
        AdGroupCreateWorkflowPrimaryInput, pydantic.Field(alias="primaryInput")
    ]

    campaign_id: Annotated[Nullable[str], pydantic.Field(alias="campaignId")]

    advanced_input: Annotated[
        Optional[AdGroupWorkflowAdvancedInput], pydantic.Field(alias="advancedInput")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["advancedInput"])
        nullable_fields = set(["campaignId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdGroupCreateWorkflowInput.model_rebuild()
except NameError:
    pass
