"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupWorkflowAssociateBidListInputTypedDict(TypedDict):
    bid_list_id: str
    is_enabled: NotRequired[Nullable[bool]]
    is_default_for_dimension: NotRequired[Nullable[bool]]


class AdGroupWorkflowAssociateBidListInput(BaseModel):
    bid_list_id: Annotated[str, pydantic.Field(alias="bidListId")]

    is_enabled: Annotated[OptionalNullable[bool], pydantic.Field(alias="isEnabled")] = (
        UNSET
    )

    is_default_for_dimension: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isDefaultForDimension")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["isEnabled", "isDefaultForDimension"])
        nullable_fields = set(["isEnabled", "isDefaultForDimension"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdGroupWorkflowAssociateBidListInput.model_rebuild()
except NameError:
    pass
