"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgroupworkflow import AdGroupWorkflow, AdGroupWorkflowTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupPayloadTypedDict(TypedDict):
    ad_group: NotRequired[AdGroupWorkflowTypedDict]


class AdGroupPayload(BaseModel):
    ad_group: Annotated[Optional[AdGroupWorkflow], pydantic.Field(alias="adGroup")] = (
        None
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["adGroup"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AdGroupPayload.model_rebuild()
except NameError:
    pass
