"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .allocationtype import AllocationType
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdGroupWorkflowBudgetInputTypedDict(TypedDict):
    allocation_type: NotRequired[AllocationType]
    budget_in_advertiser_currency: NotRequired[Nullable[float]]
    budget_in_impressions: NotRequired[Nullable[int]]
    daily_target_in_advertiser_currency: NotRequired[Nullable[float]]
    daily_target_in_impressions: NotRequired[Nullable[int]]


class AdGroupWorkflowBudgetInput(BaseModel):
    allocation_type: Annotated[
        Optional[AllocationType], pydantic.Field(alias="allocationType")
    ] = None

    budget_in_advertiser_currency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="budgetInAdvertiserCurrency")
    ] = UNSET

    budget_in_impressions: Annotated[
        OptionalNullable[int], pydantic.Field(alias="budgetInImpressions")
    ] = UNSET

    daily_target_in_advertiser_currency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="dailyTargetInAdvertiserCurrency")
    ] = UNSET

    daily_target_in_impressions: Annotated[
        OptionalNullable[int], pydantic.Field(alias="dailyTargetInImpressions")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "allocationType",
                "budgetInAdvertiserCurrency",
                "budgetInImpressions",
                "dailyTargetInAdvertiserCurrency",
                "dailyTargetInImpressions",
            ]
        )
        nullable_fields = set(
            [
                "budgetInAdvertiserCurrency",
                "budgetInImpressions",
                "dailyTargetInAdvertiserCurrency",
                "dailyTargetInImpressions",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdGroupWorkflowBudgetInput.model_rebuild()
except NameError:
    pass
