"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AdGroupChannel(str, Enum):
    OTHER = "Other"
    DISPLAY = "Display"
    VIDEO = "Video"
    AUDIO = "Audio"
    NATIVE = "Native"
    NATIVE_DISPLAY = "NativeDisplay"
    NATIVE_VIDEO = "NativeVideo"
    TV = "TV"
    OUT_OF_HOME = "OutOfHome"
