"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AtmosphericCondition(str, Enum):
    UNKNOWN = "Unknown"
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    VERY_HIGH = "VeryHigh"
    LOW_FORECAST = "LowForecast"
    MEDIUM_FORECAST = "MediumForecast"
    HIGH_FORECAST = "HighForecast"
    VERY_HIGH_FORECAST = "VeryHighForecast"
