"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AudienceReachPercentageTier(str, Enum):
    UNKNOWN = "Unknown"
    TIER1 = "Tier1"
    TIER2 = "Tier2"
    TIER3 = "Tier3"
    TIER4 = "Tier4"
