"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adstxtsellertype import AdsTxtSellerType
from .atmosphericcondition import AtmosphericCondition
from .audiencereachpercentagetier import AudienceReachPercentageTier
from .browser import Browser
from .browserinput import BrowserInput
from .contentduration import ContentDuration
from .contenttransparency import ContentTransparency
from .decimalrange import DecimalRange, DecimalRangeTypedDict
from .devicetype import DeviceType
from .doubleverifybotavoidance import DoubleVerifyBotAvoidance
from .doubleverifydisplayviewability import DoubleVerifyDisplayViewability
from .doubleverifyvideoviewability import DoubleVerifyVideoViewability
from .factualproximitytargetinput import (
    FactualProximityTargetInput,
    FactualProximityTargetInputTypedDict,
)
from .frequencyadjustmentinput import (
    FrequencyAdjustmentInput,
    FrequencyAdjustmentInputTypedDict,
)
from .fullreferrerurl import FullReferrerURL
from .geofencethirdpartydataandbrandinput import (
    GeofenceThirdPartyDataAndBrandInput,
    GeofenceThirdPartyDataAndBrandInputTypedDict,
)
from .idiosyncraticsegment import IdiosyncraticSegment
from .int32range import Int32Range, Int32RangeTypedDict
from .integralvideoviewabilityinput import IntegralVideoViewabilityInput
from .integralviewabilityinput import IntegralViewabilityInput
from .internetconnectiontype import InternetConnectionType
from .internetconnectiontypeinput import InternetConnectionTypeInput
from .likelyrefreshrate import LikelyRefreshRate
from .livestream import Livestream
from .markettypebidlist import MarketTypeBidList
from .nativecontexttype import NativeContextType
from .nativeplacementtype import NativePlacementType
from .peer39viewabilityinput import Peer39ViewabilityInput
from .productionquality import ProductionQuality
from .productionqualityinput import ProductionQualityInput
from .renderingcontext import RenderingContext
from .rewarded import Rewarded
from .rtbasiaviewability import RTBAsiaViewability
from .tencentpagequalityinput import TencentPageQualityInput
from .videomutedstate import VideoMutedState
from .videoplaybacktype import VideoPlaybackType
from .videoplayersize import VideoPlayerSize
from .videoquality import VideoQuality
from .videoskippability import VideoSkippability
from .volumecontrolpriority import VolumeControlPriority
from .weathercondition import WeatherCondition
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class BidLineCreateInputTypedDict(TypedDict):
    ad_format_id: NotRequired[Nullable[str]]
    domain_fragment: NotRequired[Nullable[str]]
    universal_category_taxonomy_id: NotRequired[Nullable[str]]
    browser: NotRequired[Browser]
    browser_id: NotRequired[BrowserInput]
    carrier_id: NotRequired[Nullable[str]]
    device_model_id: NotRequired[Nullable[int]]
    device_type: NotRequired[DeviceType]
    geo_segment_id: NotRequired[Nullable[str]]
    hour_of_week: NotRequired[Nullable[int]]
    language_id: NotRequired[Nullable[str]]
    os_name: NotRequired[Nullable[str]]
    private_contract_id: NotRequired[Nullable[str]]
    recency_window_in_minutes: NotRequired[Int32RangeTypedDict]
    rendering_context: NotRequired[RenderingContext]
    supply_vendor_id: NotRequired[Nullable[str]]
    temperature_bucket_in_celsius: NotRequired[DecimalRangeTypedDict]
    ads_txt_seller_type: NotRequired[AdsTxtSellerType]
    video_muted_state: NotRequired[VideoMutedState]
    video_playback_type: NotRequired[VideoPlaybackType]
    video_player_size: NotRequired[VideoPlayerSize]
    video_quality: NotRequired[VideoQuality]
    video_skippability: NotRequired[VideoSkippability]
    factual_proximity_target: NotRequired[FactualProximityTargetInputTypedDict]
    impression_placement_value: NotRequired[Nullable[str]]
    video_truth_score_range: NotRequired[DecimalRangeTypedDict]
    video_viewability_score_range: NotRequired[DecimalRangeTypedDict]
    display_viewability_score_range: NotRequired[DecimalRangeTypedDict]
    peer39_language_id: NotRequired[Nullable[str]]
    double_verify_bot_avoidance_category: NotRequired[DoubleVerifyBotAvoidance]
    contextual_app_category_id: NotRequired[Nullable[str]]
    publisher_id: NotRequired[Nullable[str]]
    integral_viewability_category_id: NotRequired[Nullable[str]]
    integral_viewability_category: NotRequired[IntegralViewabilityInput]
    integral_video_viewability_category_id: NotRequired[Nullable[str]]
    integral_video_viewability_category: NotRequired[IntegralVideoViewabilityInput]
    double_verify_viewability_category: NotRequired[DoubleVerifyDisplayViewability]
    double_verify_video_viewability_category: NotRequired[DoubleVerifyVideoViewability]
    peer39_viewability_category_id: NotRequired[Nullable[str]]
    peer39_viewability_category: NotRequired[Peer39ViewabilityInput]
    video_completion_rate_score_range: NotRequired[DecimalRangeTypedDict]
    internet_connection_input: NotRequired[InternetConnectionTypeInput]
    internet_connection_type_id: NotRequired[InternetConnectionTypeInput]
    internet_connection: NotRequired[InternetConnectionType]
    rtb_asia_page_quality_category: NotRequired[RTBAsiaViewability]
    rtb_asia_video_page_quality_category: NotRequired[RTBAsiaViewability]
    supply_path_optimization_list_id: NotRequired[Nullable[int]]
    market_type: NotRequired[MarketTypeBidList]
    weather_condition: NotRequired[WeatherCondition]
    frequency_adjustment: NotRequired[FrequencyAdjustmentInputTypedDict]
    seller_domain: NotRequired[Nullable[str]]
    digital_out_of_home_venue_type_id: NotRequired[Nullable[str]]
    native_placement_type: NotRequired[NativePlacementType]
    native_context_type: NotRequired[NativeContextType]
    idiosyncratic_segment: NotRequired[IdiosyncraticSegment]
    tencent_page_quality_category: NotRequired[TencentPageQualityInput]
    domain_class_id: NotRequired[Nullable[int]]
    geofence_third_party_data_and_brand: NotRequired[
        GeofenceThirdPartyDataAndBrandInputTypedDict
    ]
    genre_id: NotRequired[Nullable[str]]
    livestream: NotRequired[Livestream]
    production_quality: NotRequired[ProductionQuality]
    production_quality_id: NotRequired[ProductionQualityInput]
    content_rating_id: NotRequired[Nullable[str]]
    content_duration: NotRequired[ContentDuration]
    quality_score_range: NotRequired[DecimalRangeTypedDict]
    atmospheric_condition: NotRequired[AtmosphericCondition]
    marketplace_id: NotRequired[Nullable[str]]
    audience_reach_percentage_tier: NotRequired[AudienceReachPercentageTier]
    content_transparency: NotRequired[ContentTransparency]
    full_referrer_url: NotRequired[FullReferrerURL]
    likely_refresh_rate: NotRequired[LikelyRefreshRate]
    rewarded: NotRequired[Rewarded]
    feed_id: NotRequired[Nullable[int]]
    live_event_id: NotRequired[Nullable[str]]
    live_event_type_id: NotRequired[Nullable[str]]
    extended_zip_code_group_segment_third_party_data_id: NotRequired[Nullable[int]]
    content_language_id: NotRequired[Nullable[str]]
    ad_to_content_ratio_range: NotRequired[DecimalRangeTypedDict]
    ads_in_view_range: NotRequired[DecimalRangeTypedDict]
    bid_adjustment: NotRequired[float]
    volume_control_priority: NotRequired[VolumeControlPriority]
    max_bid: NotRequired[Nullable[float]]


class BidLineCreateInput(BaseModel):
    ad_format_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="adFormatId")
    ] = UNSET

    domain_fragment: Annotated[
        OptionalNullable[str], pydantic.Field(alias="domainFragment")
    ] = UNSET

    universal_category_taxonomy_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="universalCategoryTaxonomyId")
    ] = UNSET

    browser: Optional[Browser] = None

    browser_id: Annotated[Optional[BrowserInput], pydantic.Field(alias="browserId")] = (
        None
    )

    carrier_id: Annotated[OptionalNullable[str], pydantic.Field(alias="carrierId")] = (
        UNSET
    )

    device_model_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="deviceModelId")
    ] = UNSET

    device_type: Annotated[Optional[DeviceType], pydantic.Field(alias="deviceType")] = (
        None
    )

    geo_segment_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="geoSegmentId")
    ] = UNSET

    hour_of_week: Annotated[
        OptionalNullable[int], pydantic.Field(alias="hourOfWeek")
    ] = UNSET

    language_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="languageId")
    ] = UNSET

    os_name: Annotated[OptionalNullable[str], pydantic.Field(alias="osName")] = UNSET

    private_contract_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="privateContractId")
    ] = UNSET

    recency_window_in_minutes: Annotated[
        Optional[Int32Range], pydantic.Field(alias="recencyWindowInMinutes")
    ] = None

    rendering_context: Annotated[
        Optional[RenderingContext], pydantic.Field(alias="renderingContext")
    ] = None

    supply_vendor_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="supplyVendorId")
    ] = UNSET

    temperature_bucket_in_celsius: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="temperatureBucketInCelsius")
    ] = None

    ads_txt_seller_type: Annotated[
        Optional[AdsTxtSellerType], pydantic.Field(alias="adsTxtSellerType")
    ] = None

    video_muted_state: Annotated[
        Optional[VideoMutedState], pydantic.Field(alias="videoMutedState")
    ] = None

    video_playback_type: Annotated[
        Optional[VideoPlaybackType], pydantic.Field(alias="videoPlaybackType")
    ] = None

    video_player_size: Annotated[
        Optional[VideoPlayerSize], pydantic.Field(alias="videoPlayerSize")
    ] = None

    video_quality: Annotated[
        Optional[VideoQuality], pydantic.Field(alias="videoQuality")
    ] = None

    video_skippability: Annotated[
        Optional[VideoSkippability], pydantic.Field(alias="videoSkippability")
    ] = None

    factual_proximity_target: Annotated[
        Optional[FactualProximityTargetInput],
        pydantic.Field(alias="factualProximityTarget"),
    ] = None

    impression_placement_value: Annotated[
        OptionalNullable[str], pydantic.Field(alias="impressionPlacementValue")
    ] = UNSET

    video_truth_score_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="videoTruthScoreRange")
    ] = None

    video_viewability_score_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="videoViewabilityScoreRange")
    ] = None

    display_viewability_score_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="displayViewabilityScoreRange")
    ] = None

    peer39_language_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="peer39LanguageId")
    ] = UNSET

    double_verify_bot_avoidance_category: Annotated[
        Optional[DoubleVerifyBotAvoidance],
        pydantic.Field(alias="doubleVerifyBotAvoidanceCategory"),
    ] = None

    contextual_app_category_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="contextualAppCategoryId")
    ] = UNSET

    publisher_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="publisherId")
    ] = UNSET

    integral_viewability_category_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="integralViewabilityCategoryId")
    ] = UNSET

    integral_viewability_category: Annotated[
        Optional[IntegralViewabilityInput],
        pydantic.Field(alias="integralViewabilityCategory"),
    ] = None

    integral_video_viewability_category_id: Annotated[
        OptionalNullable[str],
        pydantic.Field(alias="integralVideoViewabilityCategoryId"),
    ] = UNSET

    integral_video_viewability_category: Annotated[
        Optional[IntegralVideoViewabilityInput],
        pydantic.Field(alias="integralVideoViewabilityCategory"),
    ] = None

    double_verify_viewability_category: Annotated[
        Optional[DoubleVerifyDisplayViewability],
        pydantic.Field(alias="doubleVerifyViewabilityCategory"),
    ] = None

    double_verify_video_viewability_category: Annotated[
        Optional[DoubleVerifyVideoViewability],
        pydantic.Field(alias="doubleVerifyVideoViewabilityCategory"),
    ] = None

    peer39_viewability_category_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="peer39ViewabilityCategoryId")
    ] = UNSET

    peer39_viewability_category: Annotated[
        Optional[Peer39ViewabilityInput],
        pydantic.Field(alias="peer39ViewabilityCategory"),
    ] = None

    video_completion_rate_score_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="videoCompletionRateScoreRange")
    ] = None

    internet_connection_input: Annotated[
        Optional[InternetConnectionTypeInput],
        pydantic.Field(alias="internetConnectionInput"),
    ] = None

    internet_connection_type_id: Annotated[
        Optional[InternetConnectionTypeInput],
        pydantic.Field(alias="internetConnectionTypeId"),
    ] = None

    internet_connection: Annotated[
        Optional[InternetConnectionType], pydantic.Field(alias="internetConnection")
    ] = None

    rtb_asia_page_quality_category: Annotated[
        Optional[RTBAsiaViewability], pydantic.Field(alias="rtbAsiaPageQualityCategory")
    ] = None

    rtb_asia_video_page_quality_category: Annotated[
        Optional[RTBAsiaViewability],
        pydantic.Field(alias="rtbAsiaVideoPageQualityCategory"),
    ] = None

    supply_path_optimization_list_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="supplyPathOptimizationListId")
    ] = UNSET

    market_type: Annotated[
        Optional[MarketTypeBidList], pydantic.Field(alias="marketType")
    ] = None

    weather_condition: Annotated[
        Optional[WeatherCondition], pydantic.Field(alias="weatherCondition")
    ] = None

    frequency_adjustment: Annotated[
        Optional[FrequencyAdjustmentInput], pydantic.Field(alias="frequencyAdjustment")
    ] = None

    seller_domain: Annotated[
        OptionalNullable[str], pydantic.Field(alias="sellerDomain")
    ] = UNSET

    digital_out_of_home_venue_type_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="digitalOutOfHomeVenueTypeId")
    ] = UNSET

    native_placement_type: Annotated[
        Optional[NativePlacementType], pydantic.Field(alias="nativePlacementType")
    ] = None

    native_context_type: Annotated[
        Optional[NativeContextType], pydantic.Field(alias="nativeContextType")
    ] = None

    idiosyncratic_segment: Annotated[
        Optional[IdiosyncraticSegment], pydantic.Field(alias="idiosyncraticSegment")
    ] = None

    tencent_page_quality_category: Annotated[
        Optional[TencentPageQualityInput],
        pydantic.Field(alias="tencentPageQualityCategory"),
    ] = None

    domain_class_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="domainClassId")
    ] = UNSET

    geofence_third_party_data_and_brand: Annotated[
        Optional[GeofenceThirdPartyDataAndBrandInput],
        pydantic.Field(alias="geofenceThirdPartyDataAndBrand"),
    ] = None

    genre_id: Annotated[OptionalNullable[str], pydantic.Field(alias="genreId")] = UNSET

    livestream: Optional[Livestream] = None

    production_quality: Annotated[
        Optional[ProductionQuality], pydantic.Field(alias="productionQuality")
    ] = None

    production_quality_id: Annotated[
        Optional[ProductionQualityInput], pydantic.Field(alias="productionQualityId")
    ] = None

    content_rating_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="contentRatingId")
    ] = UNSET

    content_duration: Annotated[
        Optional[ContentDuration], pydantic.Field(alias="contentDuration")
    ] = None

    quality_score_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="qualityScoreRange")
    ] = None

    atmospheric_condition: Annotated[
        Optional[AtmosphericCondition], pydantic.Field(alias="atmosphericCondition")
    ] = None

    marketplace_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="marketplaceId")
    ] = UNSET

    audience_reach_percentage_tier: Annotated[
        Optional[AudienceReachPercentageTier],
        pydantic.Field(alias="audienceReachPercentageTier"),
    ] = None

    content_transparency: Annotated[
        Optional[ContentTransparency], pydantic.Field(alias="contentTransparency")
    ] = None

    full_referrer_url: Annotated[
        Optional[FullReferrerURL], pydantic.Field(alias="fullReferrerUrl")
    ] = None

    likely_refresh_rate: Annotated[
        Optional[LikelyRefreshRate], pydantic.Field(alias="likelyRefreshRate")
    ] = None

    rewarded: Optional[Rewarded] = None

    feed_id: Annotated[OptionalNullable[int], pydantic.Field(alias="feedId")] = UNSET

    live_event_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="liveEventId")
    ] = UNSET

    live_event_type_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="liveEventTypeId")
    ] = UNSET

    extended_zip_code_group_segment_third_party_data_id: Annotated[
        OptionalNullable[int],
        pydantic.Field(alias="extendedZipCodeGroupSegmentThirdPartyDataId"),
    ] = UNSET

    content_language_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="contentLanguageId")
    ] = UNSET

    ad_to_content_ratio_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="adToContentRatioRange")
    ] = None

    ads_in_view_range: Annotated[
        Optional[DecimalRange], pydantic.Field(alias="adsInViewRange")
    ] = None

    bid_adjustment: Annotated[
        Optional[float], pydantic.Field(alias="bidAdjustment")
    ] = None

    volume_control_priority: Annotated[
        Optional[VolumeControlPriority], pydantic.Field(alias="volumeControlPriority")
    ] = None

    max_bid: Annotated[OptionalNullable[float], pydantic.Field(alias="maxBid")] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "adFormatId",
                "domainFragment",
                "universalCategoryTaxonomyId",
                "browser",
                "browserId",
                "carrierId",
                "deviceModelId",
                "deviceType",
                "geoSegmentId",
                "hourOfWeek",
                "languageId",
                "osName",
                "privateContractId",
                "recencyWindowInMinutes",
                "renderingContext",
                "supplyVendorId",
                "temperatureBucketInCelsius",
                "adsTxtSellerType",
                "videoMutedState",
                "videoPlaybackType",
                "videoPlayerSize",
                "videoQuality",
                "videoSkippability",
                "factualProximityTarget",
                "impressionPlacementValue",
                "videoTruthScoreRange",
                "videoViewabilityScoreRange",
                "displayViewabilityScoreRange",
                "peer39LanguageId",
                "doubleVerifyBotAvoidanceCategory",
                "contextualAppCategoryId",
                "publisherId",
                "integralViewabilityCategoryId",
                "integralViewabilityCategory",
                "integralVideoViewabilityCategoryId",
                "integralVideoViewabilityCategory",
                "doubleVerifyViewabilityCategory",
                "doubleVerifyVideoViewabilityCategory",
                "peer39ViewabilityCategoryId",
                "peer39ViewabilityCategory",
                "videoCompletionRateScoreRange",
                "internetConnectionInput",
                "internetConnectionTypeId",
                "internetConnection",
                "rtbAsiaPageQualityCategory",
                "rtbAsiaVideoPageQualityCategory",
                "supplyPathOptimizationListId",
                "marketType",
                "weatherCondition",
                "frequencyAdjustment",
                "sellerDomain",
                "digitalOutOfHomeVenueTypeId",
                "nativePlacementType",
                "nativeContextType",
                "idiosyncraticSegment",
                "tencentPageQualityCategory",
                "domainClassId",
                "geofenceThirdPartyDataAndBrand",
                "genreId",
                "livestream",
                "productionQuality",
                "productionQualityId",
                "contentRatingId",
                "contentDuration",
                "qualityScoreRange",
                "atmosphericCondition",
                "marketplaceId",
                "audienceReachPercentageTier",
                "contentTransparency",
                "fullReferrerUrl",
                "likelyRefreshRate",
                "rewarded",
                "feedId",
                "liveEventId",
                "liveEventTypeId",
                "extendedZipCodeGroupSegmentThirdPartyDataId",
                "contentLanguageId",
                "adToContentRatioRange",
                "adsInViewRange",
                "bidAdjustment",
                "volumeControlPriority",
                "maxBid",
            ]
        )
        nullable_fields = set(
            [
                "adFormatId",
                "domainFragment",
                "universalCategoryTaxonomyId",
                "carrierId",
                "deviceModelId",
                "geoSegmentId",
                "hourOfWeek",
                "languageId",
                "osName",
                "privateContractId",
                "supplyVendorId",
                "impressionPlacementValue",
                "peer39LanguageId",
                "contextualAppCategoryId",
                "publisherId",
                "integralViewabilityCategoryId",
                "integralVideoViewabilityCategoryId",
                "peer39ViewabilityCategoryId",
                "supplyPathOptimizationListId",
                "sellerDomain",
                "digitalOutOfHomeVenueTypeId",
                "domainClassId",
                "genreId",
                "contentRatingId",
                "marketplaceId",
                "feedId",
                "liveEventId",
                "liveEventTypeId",
                "extendedZipCodeGroupSegmentThirdPartyDataId",
                "contentLanguageId",
                "maxBid",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    BidLineCreateInput.model_rebuild()
except NameError:
    pass
