"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class BidListSource(str, Enum):
    USER = "User"
    SYSTEM_MANUAL = "SystemManual"
    SYSTEM_AUTO = "SystemAuto"
    USER_BULK_EDIT = "UserBulkEdit"
    SYSTEM_AUTO_FOR_COOKIE_LESS = "SystemAutoForCookieLess"
    FREQUENCY_MIGRATION = "FrequencyMigration"
    SYSTEM_AUTO_FOR_COMMITMENT_PRIORITIZATION = "SystemAutoForCommitmentPrioritization"
    SYSTEM_AUTO_FOR_WIN_RATE_EXCLUSION = "SystemAutoForWinRateExclusion"
    SYSTEM_AUTO_FOR_ALWAYS_ON_DEALS = "SystemAutoForAlwaysOnDeals"
    SYSTEM_AUTO_FOR_MARKETPLACE = "SystemAutoForMarketplace"
    SYSTEM_AUTO_FOR_ENDEAVOR_TARGETING = "SystemAutoForEndeavorTargeting"
    SYSTEM_AUTO_FOR_COMMITMENT_TARGETING = "SystemAutoForCommitmentTargeting"
