"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class BidListAssociateBehavior(str, Enum):
    DO_NOT_ASSOCIATE = "DoNotAssociate"
    ASSOCIATE = "Associate"
    ASSOCIATE_AND_ENABLE = "AssociateAndEnable"
