"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class BrowserInput(str, Enum):
    OTHER = "Other"
    INTERNET_EXPLORER7 = "InternetExplorer7"
    INTERNET_EXPLORER8 = "InternetExplorer8"
    INTERNET_EXPLORER9 = "InternetExplorer9"
    FIREFOX = "Firefox"
    CHROME = "Chrome"
    SAFARI = "Safari"
    OPERA = "Opera"
    INTERNET_EXPLORER10 = "InternetExplorer10"
    INTERNET_EXPLORER11 = "InternetExplorer11"
    IN_APP = "InApp"
    EDGE = "Edge"
    BAIDU = "Baidu"
    YANDEX = "Yandex"
    WEB_VIEW = "WebView"
