"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ttd_workflows.types import BaseModel
from typing_extensions import TypedDict


class BulkJobSubmitResponseTypedDict(TypedDict):
    id: int
    r"""ID of the bulk job."""


class BulkJobSubmitResponse(BaseModel):
    id: int
    r"""ID of the bulk job."""
