"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .pubapimethodtype import PubAPIMethodType
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class CallPubAPIWorkflowInputTypedDict(TypedDict):
    method_type: PubAPIMethodType
    endpoint: Nullable[str]
    data_body: NotRequired[Nullable[str]]


class CallPubAPIWorkflowInput(BaseModel):
    method_type: Annotated[PubAPIMethodType, pydantic.Field(alias="methodType")]

    endpoint: Nullable[str]

    data_body: Annotated[OptionalNullable[str], pydantic.Field(alias="dataBody")] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["dataBody"]
        nullable_fields = ["endpoint", "dataBody"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
