"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .audienceunlimitedtierinput import AudienceUnlimitedTierInput
from .tradingmodeupdateinput import TradingModeUpdateInput
import pydantic
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignUpdateWorkflowTradingModeSettingsInputTypedDict(TypedDict):
    mode: NotRequired[TradingModeUpdateInput]
    audience_unlimited_tier: NotRequired[AudienceUnlimitedTierInput]


class CampaignUpdateWorkflowTradingModeSettingsInput(BaseModel):
    mode: Optional[TradingModeUpdateInput] = None

    audience_unlimited_tier: Annotated[
        Optional[AudienceUnlimitedTierInput],
        pydantic.Field(alias="audienceUnlimitedTier"),
    ] = None
