"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaigncreatepassthroughfeesinput import (
    CampaignCreatePassThroughFeesInput,
    CampaignCreatePassThroughFeesInputTypedDict,
)
from datetime import datetime
import pydantic
from ttd_workflows.types import BaseModel
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowPassThroughFeeCardInputTypedDict(TypedDict):
    pass_through_fees: List[CampaignCreatePassThroughFeesInputTypedDict]
    start_date_utc: NotRequired[datetime]


class CampaignCreateWorkflowPassThroughFeeCardInput(BaseModel):
    pass_through_fees: Annotated[
        List[CampaignCreatePassThroughFeesInput],
        pydantic.Field(alias="passThroughFees"),
    ]

    start_date_utc: Annotated[
        Optional[datetime], pydantic.Field(alias="startDateUtc")
    ] = None
