"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaignchannel import CampaignChannel
from .campaigncreateroigoalinput import (
    CampaignCreateROIGoalInput,
    CampaignCreateROIGoalInputTypedDict,
)
from .campaignflightcreationinput import (
    CampaignFlightCreationInput,
    CampaignFlightCreationInputTypedDict,
)
import pydantic
from ttd_workflows.types import BaseModel
from typing import List
from typing_extensions import Annotated, TypedDict


class CampaignCreationInputTypedDict(TypedDict):
    r"""Schema with required fields for creating a new campaign"""

    advertiser_id: str
    r"""The platform ID of the advertiser that owns this Campaign."""
    campaign_name: str
    r"""The name of the Campaign."""
    primary_channel: CampaignChannel
    primary_goal: CampaignCreateROIGoalInputTypedDict
    campaign_flights: List[CampaignFlightCreationInputTypedDict]
    r"""The List of flights associated with the Campaign."""


class CampaignCreationInput(BaseModel):
    r"""Schema with required fields for creating a new campaign"""

    advertiser_id: Annotated[str, pydantic.Field(alias="advertiserId")]
    r"""The platform ID of the advertiser that owns this Campaign."""

    campaign_name: Annotated[str, pydantic.Field(alias="campaignName")]
    r"""The name of the Campaign."""

    primary_channel: Annotated[CampaignChannel, pydantic.Field(alias="primaryChannel")]

    primary_goal: Annotated[
        CampaignCreateROIGoalInput, pydantic.Field(alias="primaryGoal")
    ]

    campaign_flights: Annotated[
        List[CampaignFlightCreationInput], pydantic.Field(alias="campaignFlights")
    ]
    r"""The List of flights associated with the Campaign."""
