"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignVersionWorkflowTypedDict(TypedDict):
    id: Nullable[str]
    version: NotRequired[Nullable[str]]
    budgeting_version: NotRequired[Nullable[str]]


class CampaignVersionWorkflow(BaseModel):
    id: Annotated[Nullable[str], pydantic.Field(alias="Id")]

    version: OptionalNullable[str] = UNSET

    budgeting_version: Annotated[
        OptionalNullable[str], pydantic.Field(alias="budgetingVersion")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["version", "budgetingVersion"]
        nullable_fields = ["Id", "version", "budgetingVersion"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
