"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaignpacingmode import CampaignPacingMode
import pydantic
from ttd_workflows.types import BaseModel
from typing_extensions import Annotated, TypedDict


class CampaignUpdateWorkflowBudgetInputTypedDict(TypedDict):
    pacing_mode: CampaignPacingMode


class CampaignUpdateWorkflowBudgetInput(BaseModel):
    pacing_mode: Annotated[CampaignPacingMode, pydantic.Field(alias="pacingMode")]


try:
    CampaignUpdateWorkflowBudgetInput.model_rebuild()
except NameError:
    pass
