"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaignupdateworkflowadvancedinput import (
    CampaignUpdateWorkflowAdvancedInput,
    CampaignUpdateWorkflowAdvancedInputTypedDict,
)
from .campaignupdateworkflowprimaryinput import (
    CampaignUpdateWorkflowPrimaryInput,
    CampaignUpdateWorkflowPrimaryInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, Nullable, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignUpdateWorkflowInputTypedDict(TypedDict):
    id: Nullable[str]
    primary_input: NotRequired[CampaignUpdateWorkflowPrimaryInputTypedDict]
    advanced_input: NotRequired[CampaignUpdateWorkflowAdvancedInputTypedDict]


class CampaignUpdateWorkflowInput(BaseModel):
    id: Nullable[str]

    primary_input: Annotated[
        Optional[CampaignUpdateWorkflowPrimaryInput],
        pydantic.Field(alias="primaryInput"),
    ] = None

    advanced_input: Annotated[
        Optional[CampaignUpdateWorkflowAdvancedInput],
        pydantic.Field(alias="advancedInput"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["primaryInput", "advancedInput"])
        nullable_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignUpdateWorkflowInput.model_rebuild()
except NameError:
    pass
