"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaigncreateadgroupinput import (
    CampaignCreateAdGroupInput,
    CampaignCreateAdGroupInputTypedDict,
)
from .campaigncreateworkflowadvancedinput import (
    CampaignCreateWorkflowAdvancedInput,
    CampaignCreateWorkflowAdvancedInputTypedDict,
)
from .campaigncreateworkflowprimaryinput import (
    CampaignCreateWorkflowPrimaryInput,
    CampaignCreateWorkflowPrimaryInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowInputTypedDict(TypedDict):
    campaign_create_workflow_primary_input: CampaignCreateWorkflowPrimaryInputTypedDict
    campaign_create_advanced_input: NotRequired[
        CampaignCreateWorkflowAdvancedInputTypedDict
    ]
    ad_groups: NotRequired[Nullable[List[CampaignCreateAdGroupInputTypedDict]]]
    validation_only: NotRequired[Nullable[bool]]


class CampaignCreateWorkflowInput(BaseModel):
    campaign_create_workflow_primary_input: Annotated[
        CampaignCreateWorkflowPrimaryInput,
        pydantic.Field(alias="campaignCreateWorkflowPrimaryInput"),
    ]

    campaign_create_advanced_input: Annotated[
        Optional[CampaignCreateWorkflowAdvancedInput],
        pydantic.Field(alias="campaignCreateAdvancedInput"),
    ] = None

    ad_groups: Annotated[
        OptionalNullable[List[CampaignCreateAdGroupInput]],
        pydantic.Field(alias="adGroups"),
    ] = UNSET

    validation_only: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="validationOnly")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["campaignCreateAdvancedInput", "adGroups", "validationOnly"]
        nullable_fields = ["adGroups", "validationOnly"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
