"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaignchanneltype import CampaignChannelType
from .campaigncreateworkflowbudgetinput import (
    CampaignCreateWorkflowBudgetInput,
    CampaignCreateWorkflowBudgetInputTypedDict,
)
from .campaigncreateworkflowincrementalreachcampaignsetting import (
    CampaignCreateWorkflowIncrementalReachCampaignSetting,
    CampaignCreateWorkflowIncrementalReachCampaignSettingTypedDict,
)
from .campaignworkflowcampaignconversionreportingcolumninput import (
    CampaignWorkflowCampaignConversionReportingColumnInput,
    CampaignWorkflowCampaignConversionReportingColumnInputTypedDict,
)
from .campaignworkflowroigoalinput import (
    CampaignWorkflowROIGoalInput,
    CampaignWorkflowROIGoalInputTypedDict,
)
from .customcpatype import CustomCPAType
from .customroastype import CustomROASType
from datetime import datetime
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowPrimaryInputTypedDict(TypedDict):
    advertiser_id: str
    name: str
    primary_channel: CampaignChannelType
    primary_goal: CampaignWorkflowROIGoalInputTypedDict
    description: NotRequired[Nullable[str]]
    campaign_group_id: NotRequired[Nullable[int]]
    time_zone: NotRequired[Nullable[str]]
    custom_cpa_click_weight: NotRequired[Nullable[float]]
    custom_cpa_viewthrough_weight: NotRequired[Nullable[float]]
    custom_cpa_type: NotRequired[CustomCPAType]
    custom_roas_type: NotRequired[CustomROASType]
    impressions_only_budgeting_cpm: NotRequired[Nullable[float]]
    end_date_in_utc: NotRequired[Nullable[datetime]]
    seed_id: NotRequired[Nullable[str]]
    campaign_conversion_reporting_columns: NotRequired[
        Nullable[List[CampaignWorkflowCampaignConversionReportingColumnInputTypedDict]]
    ]
    is_managed_by_ttd: NotRequired[Nullable[bool]]
    secondary_goal: NotRequired[CampaignWorkflowROIGoalInputTypedDict]
    tertiary_goal: NotRequired[CampaignWorkflowROIGoalInputTypedDict]
    custom_label_names: NotRequired[Nullable[List[str]]]
    start_date_in_utc: NotRequired[Nullable[datetime]]
    budget: NotRequired[CampaignCreateWorkflowBudgetInputTypedDict]
    campaign_incremental_reach_setting: NotRequired[
        CampaignCreateWorkflowIncrementalReachCampaignSettingTypedDict
    ]


class CampaignCreateWorkflowPrimaryInput(BaseModel):
    advertiser_id: Annotated[str, pydantic.Field(alias="advertiserId")]

    name: str

    primary_channel: Annotated[
        CampaignChannelType, pydantic.Field(alias="primaryChannel")
    ]

    primary_goal: Annotated[
        CampaignWorkflowROIGoalInput, pydantic.Field(alias="primaryGoal")
    ]

    description: OptionalNullable[str] = UNSET

    campaign_group_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="campaignGroupId")
    ] = UNSET

    time_zone: Annotated[OptionalNullable[str], pydantic.Field(alias="timeZone")] = (
        UNSET
    )

    custom_cpa_click_weight: Annotated[
        OptionalNullable[float], pydantic.Field(alias="customCPAClickWeight")
    ] = UNSET

    custom_cpa_viewthrough_weight: Annotated[
        OptionalNullable[float], pydantic.Field(alias="customCPAViewthroughWeight")
    ] = UNSET

    custom_cpa_type: Annotated[
        Optional[CustomCPAType], pydantic.Field(alias="customCPAType")
    ] = None

    custom_roas_type: Annotated[
        Optional[CustomROASType], pydantic.Field(alias="customRoasType")
    ] = None

    impressions_only_budgeting_cpm: Annotated[
        OptionalNullable[float], pydantic.Field(alias="impressionsOnlyBudgetingCpm")
    ] = UNSET

    end_date_in_utc: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="endDateInUtc")
    ] = UNSET

    seed_id: Annotated[OptionalNullable[str], pydantic.Field(alias="seedId")] = UNSET

    campaign_conversion_reporting_columns: Annotated[
        OptionalNullable[List[CampaignWorkflowCampaignConversionReportingColumnInput]],
        pydantic.Field(alias="campaignConversionReportingColumns"),
    ] = UNSET

    is_managed_by_ttd: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isManagedByTTD")
    ] = UNSET

    secondary_goal: Annotated[
        Optional[CampaignWorkflowROIGoalInput], pydantic.Field(alias="secondaryGoal")
    ] = None

    tertiary_goal: Annotated[
        Optional[CampaignWorkflowROIGoalInput], pydantic.Field(alias="tertiaryGoal")
    ] = None

    custom_label_names: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="customLabelNames")
    ] = UNSET

    start_date_in_utc: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="startDateInUtc")
    ] = UNSET

    budget: Optional[CampaignCreateWorkflowBudgetInput] = None

    campaign_incremental_reach_setting: Annotated[
        Optional[CampaignCreateWorkflowIncrementalReachCampaignSetting],
        pydantic.Field(alias="campaignIncrementalReachSetting"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "campaignGroupId",
                "timeZone",
                "customCPAClickWeight",
                "customCPAViewthroughWeight",
                "customCPAType",
                "customRoasType",
                "impressionsOnlyBudgetingCpm",
                "endDateInUtc",
                "seedId",
                "campaignConversionReportingColumns",
                "isManagedByTTD",
                "secondaryGoal",
                "tertiaryGoal",
                "customLabelNames",
                "startDateInUtc",
                "budget",
                "campaignIncrementalReachSetting",
            ]
        )
        nullable_fields = set(
            [
                "description",
                "campaignGroupId",
                "timeZone",
                "customCPAClickWeight",
                "customCPAViewthroughWeight",
                "impressionsOnlyBudgetingCpm",
                "endDateInUtc",
                "seedId",
                "campaignConversionReportingColumns",
                "isManagedByTTD",
                "customLabelNames",
                "startDateInUtc",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignCreateWorkflowPrimaryInput.model_rebuild()
except NameError:
    pass
