"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgroupcreateworkflowprimaryinput import (
    AdGroupCreateWorkflowPrimaryInput,
    AdGroupCreateWorkflowPrimaryInputTypedDict,
)
from .campaigncreateworkflowadgroupadvancedinput import (
    CampaignCreateWorkflowAdGroupAdvancedInput,
    CampaignCreateWorkflowAdGroupAdvancedInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowAdGroupInputTypedDict(TypedDict):
    primary_input: AdGroupCreateWorkflowPrimaryInputTypedDict
    advanced_input: NotRequired[CampaignCreateWorkflowAdGroupAdvancedInputTypedDict]


class CampaignCreateWorkflowAdGroupInput(BaseModel):
    primary_input: Annotated[
        AdGroupCreateWorkflowPrimaryInput, pydantic.Field(alias="primaryInput")
    ]

    advanced_input: Annotated[
        Optional[CampaignCreateWorkflowAdGroupAdvancedInput],
        pydantic.Field(alias="advancedInput"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["advancedInput"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CampaignCreateWorkflowAdGroupInput.model_rebuild()
except NameError:
    pass
