"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .customroasconfig import CustomROASConfig, CustomROASConfigTypedDict
from .productlistreportingtypeinput import ProductListReportingTypeInput
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignWorkflowCampaignConversionReportingColumnInputTypedDict(TypedDict):
    tracking_tag_id: str
    include_in_custom_cpa: bool
    reporting_column_id: int
    roas_config: NotRequired[CustomROASConfigTypedDict]
    product_list_reporting_type: NotRequired[ProductListReportingTypeInput]
    weight: NotRequired[Nullable[float]]
    cross_device_attribution_model_id: NotRequired[Nullable[str]]


class CampaignWorkflowCampaignConversionReportingColumnInput(BaseModel):
    tracking_tag_id: Annotated[str, pydantic.Field(alias="trackingTagId")]

    include_in_custom_cpa: Annotated[bool, pydantic.Field(alias="includeInCustomCPA")]

    reporting_column_id: Annotated[int, pydantic.Field(alias="reportingColumnId")]

    roas_config: Annotated[
        Optional[CustomROASConfig], pydantic.Field(alias="ROASConfig")
    ] = None

    product_list_reporting_type: Annotated[
        Optional[ProductListReportingTypeInput],
        pydantic.Field(alias="productListReportingType"),
    ] = None

    weight: OptionalNullable[float] = UNSET

    cross_device_attribution_model_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="crossDeviceAttributionModelId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "ROASConfig",
                "productListReportingType",
                "weight",
                "crossDeviceAttributionModelId",
            ]
        )
        nullable_fields = set(["weight", "crossDeviceAttributionModelId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignWorkflowCampaignConversionReportingColumnInput.model_rebuild()
except NameError:
    pass
