"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaignupdateworkflowprimaryinput import (
    CampaignUpdateWorkflowPrimaryInput,
    CampaignUpdateWorkflowPrimaryInputTypedDict,
)
from .campaignworkflowadvancedinput import (
    CampaignWorkflowAdvancedInput,
    CampaignWorkflowAdvancedInputTypedDict,
)
import pydantic
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignUpdateWorkflowInputTypedDict(TypedDict):
    primary_input: CampaignUpdateWorkflowPrimaryInputTypedDict
    advanced_input: NotRequired[CampaignWorkflowAdvancedInputTypedDict]


class CampaignUpdateWorkflowInput(BaseModel):
    primary_input: Annotated[
        CampaignUpdateWorkflowPrimaryInput, pydantic.Field(alias="primaryInput")
    ]

    advanced_input: Annotated[
        Optional[CampaignWorkflowAdvancedInput], pydantic.Field(alias="advancedInput")
    ] = None
