"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignWorkflowROIGoalInputTypedDict(TypedDict):
    maximize_reach: NotRequired[Nullable[bool]]
    maximize_ltv_incremental_reach: NotRequired[Nullable[bool]]
    cpc_in_advertiser_currency: NotRequired[Nullable[float]]
    ctr_in_percent: NotRequired[Nullable[float]]
    nielsen_otp_in_percent: NotRequired[Nullable[float]]
    cpa_in_advertiser_currency: NotRequired[Nullable[float]]
    return_on_ad_spend_percent: NotRequired[Nullable[float]]
    vcr_in_percent: NotRequired[Nullable[float]]
    viewability_in_percent: NotRequired[Nullable[float]]
    vcpm_in_advertiser_currency: NotRequired[Nullable[float]]
    cpcv_in_advertiser_currency: NotRequired[Nullable[float]]
    miaozhen_otp_in_percent: NotRequired[Nullable[float]]
    iqvia_audience_quality_index: NotRequired[Nullable[bool]]
    crossix_audience_quality_index: NotRequired[Nullable[bool]]
    iqvia_audience_quality_index_and_cost_per_target: NotRequired[Nullable[bool]]
    crossix_cost_per_target: NotRequired[Nullable[bool]]
    new_buyer_target_value: NotRequired[Nullable[int]]


class CampaignWorkflowROIGoalInput(BaseModel):
    maximize_reach: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="maximizeReach")
    ] = UNSET

    maximize_ltv_incremental_reach: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="maximizeLtvIncrementalReach")
    ] = UNSET

    cpc_in_advertiser_currency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="cpcInAdvertiserCurrency")
    ] = UNSET

    ctr_in_percent: Annotated[
        OptionalNullable[float], pydantic.Field(alias="ctrInPercent")
    ] = UNSET

    nielsen_otp_in_percent: Annotated[
        OptionalNullable[float], pydantic.Field(alias="nielsenOTPInPercent")
    ] = UNSET

    cpa_in_advertiser_currency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="cpaInAdvertiserCurrency")
    ] = UNSET

    return_on_ad_spend_percent: Annotated[
        OptionalNullable[float], pydantic.Field(alias="returnOnAdSpendPercent")
    ] = UNSET

    vcr_in_percent: Annotated[
        OptionalNullable[float], pydantic.Field(alias="vcrInPercent")
    ] = UNSET

    viewability_in_percent: Annotated[
        OptionalNullable[float], pydantic.Field(alias="viewabilityInPercent")
    ] = UNSET

    vcpm_in_advertiser_currency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="vcpmInAdvertiserCurrency")
    ] = UNSET

    cpcv_in_advertiser_currency: Annotated[
        OptionalNullable[float], pydantic.Field(alias="cpcvInAdvertiserCurrency")
    ] = UNSET

    miaozhen_otp_in_percent: Annotated[
        OptionalNullable[float], pydantic.Field(alias="miaozhenOTPInPercent")
    ] = UNSET

    iqvia_audience_quality_index: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="iqviaAudienceQualityIndex")
    ] = UNSET

    crossix_audience_quality_index: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="crossixAudienceQualityIndex")
    ] = UNSET

    iqvia_audience_quality_index_and_cost_per_target: Annotated[
        OptionalNullable[bool],
        pydantic.Field(alias="iqviaAudienceQualityIndexAndCostPerTarget"),
    ] = UNSET

    crossix_cost_per_target: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="crossixCostPerTarget")
    ] = UNSET

    new_buyer_target_value: Annotated[
        OptionalNullable[int], pydantic.Field(alias="NewBuyerTargetValue")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "maximizeReach",
                "maximizeLtvIncrementalReach",
                "cpcInAdvertiserCurrency",
                "ctrInPercent",
                "nielsenOTPInPercent",
                "cpaInAdvertiserCurrency",
                "returnOnAdSpendPercent",
                "vcrInPercent",
                "viewabilityInPercent",
                "vcpmInAdvertiserCurrency",
                "cpcvInAdvertiserCurrency",
                "miaozhenOTPInPercent",
                "iqviaAudienceQualityIndex",
                "crossixAudienceQualityIndex",
                "iqviaAudienceQualityIndexAndCostPerTarget",
                "crossixCostPerTarget",
                "NewBuyerTargetValue",
            ]
        )
        nullable_fields = set(
            [
                "maximizeReach",
                "maximizeLtvIncrementalReach",
                "cpcInAdvertiserCurrency",
                "ctrInPercent",
                "nielsenOTPInPercent",
                "cpaInAdvertiserCurrency",
                "returnOnAdSpendPercent",
                "vcrInPercent",
                "viewabilityInPercent",
                "vcpmInAdvertiserCurrency",
                "cpcvInAdvertiserCurrency",
                "miaozhenOTPInPercent",
                "iqviaAudienceQualityIndex",
                "crossixAudienceQualityIndex",
                "iqviaAudienceQualityIndexAndCostPerTarget",
                "crossixCostPerTarget",
                "NewBuyerTargetValue",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignWorkflowROIGoalInput.model_rebuild()
except NameError:
    pass
