"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .incrementalreachbrandinput import (
    IncrementalReachBrandInput,
    IncrementalReachBrandInputTypedDict,
)
from .realyticsreachsettinginput import (
    RealyticsReachSettingInput,
    RealyticsReachSettingInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowIncrementalReachCampaignSettingTypedDict(TypedDict):
    i_spot_reach_setting: NotRequired[IncrementalReachBrandInputTypedDict]
    realytics_reach_setting: NotRequired[RealyticsReachSettingInputTypedDict]
    tv_squared_reach_setting: NotRequired[IncrementalReachBrandInputTypedDict]
    samba_au_reach_setting: NotRequired[IncrementalReachBrandInputTypedDict]


class CampaignCreateWorkflowIncrementalReachCampaignSetting(BaseModel):
    i_spot_reach_setting: Annotated[
        Optional[IncrementalReachBrandInput], pydantic.Field(alias="iSpotReachSetting")
    ] = None

    realytics_reach_setting: Annotated[
        Optional[RealyticsReachSettingInput],
        pydantic.Field(alias="realyticsReachSetting"),
    ] = None

    tv_squared_reach_setting: Annotated[
        Optional[IncrementalReachBrandInput],
        pydantic.Field(alias="tvSquaredReachSetting"),
    ] = None

    samba_au_reach_setting: Annotated[
        Optional[IncrementalReachBrandInput],
        pydantic.Field(alias="sambaAuReachSetting"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "iSpotReachSetting",
                "realyticsReachSetting",
                "tvSquaredReachSetting",
                "sambaAuReachSetting",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CampaignCreateWorkflowIncrementalReachCampaignSetting.model_rebuild()
except NameError:
    pass
