"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgroupworkflow import AdGroupWorkflow, AdGroupWorkflowTypedDict
from .campaignworkflow import CampaignWorkflow, CampaignWorkflowTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignPayloadTypedDict(TypedDict):
    campaign: NotRequired[CampaignWorkflowTypedDict]
    ad_groups: NotRequired[Nullable[List[AdGroupWorkflowTypedDict]]]


class CampaignPayload(BaseModel):
    campaign: Optional[CampaignWorkflow] = None

    ad_groups: Annotated[
        OptionalNullable[List[AdGroupWorkflow]], pydantic.Field(alias="adGroups")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["campaign", "adGroups"])
        nullable_fields = set(["adGroups"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignPayload.model_rebuild()
except NameError:
    pass
