"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaigncreateworkflowpassthroughfeecardinput import (
    CampaignCreateWorkflowPassThroughFeeCardInput,
    CampaignCreateWorkflowPassThroughFeeCardInputTypedDict,
)
from .campaignworkflowflightinput import (
    CampaignWorkflowFlightInput,
    CampaignWorkflowFlightInputTypedDict,
)
from .frequencyconfig import FrequencyConfig, FrequencyConfigTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowAdvancedInputTypedDict(TypedDict):
    purchase_order_number: NotRequired[Nullable[str]]
    flights: NotRequired[Nullable[List[CampaignWorkflowFlightInputTypedDict]]]
    include_defaults_from_advertiser: NotRequired[bool]
    pass_through_fee_card: NotRequired[
        CampaignCreateWorkflowPassThroughFeeCardInputTypedDict
    ]
    caller_source: NotRequired[Nullable[str]]
    frequency_configs: NotRequired[Nullable[List[FrequencyConfigTypedDict]]]


class CampaignCreateWorkflowAdvancedInput(BaseModel):
    purchase_order_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="purchaseOrderNumber")
    ] = UNSET

    flights: OptionalNullable[List[CampaignWorkflowFlightInput]] = UNSET

    include_defaults_from_advertiser: Annotated[
        Optional[bool], pydantic.Field(alias="includeDefaultsFromAdvertiser")
    ] = None

    pass_through_fee_card: Annotated[
        Optional[CampaignCreateWorkflowPassThroughFeeCardInput],
        pydantic.Field(alias="passThroughFeeCard"),
    ] = None

    caller_source: Annotated[
        OptionalNullable[str], pydantic.Field(alias="callerSource")
    ] = UNSET

    frequency_configs: Annotated[
        OptionalNullable[List[FrequencyConfig]],
        pydantic.Field(alias="frequencyConfigs"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "purchaseOrderNumber",
                "flights",
                "includeDefaultsFromAdvertiser",
                "passThroughFeeCard",
                "callerSource",
                "frequencyConfigs",
            ]
        )
        nullable_fields = set(
            ["purchaseOrderNumber", "flights", "callerSource", "frequencyConfigs"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignCreateWorkflowAdvancedInput.model_rebuild()
except NameError:
    pass
