"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class CampaignChannel(str, Enum):
    NONE = "None"
    DISPLAY = "Display"
    AUDIO = "Audio"
    VIDEO = "Video"
    TV = "TV"
    NATIVE_VIDEO = "NativeVideo"
    NATIVE_DISPLAY = "NativeDisplay"
    DOOH = "DOOH"
