"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .incrementalreachbrandinput import (
    IncrementalReachBrandInput,
    IncrementalReachBrandInputTypedDict,
)
from .realyticsreachsettinginput import (
    RealyticsReachSettingInput,
    RealyticsReachSettingInputTypedDict,
)
import pydantic
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowIncrementalReachCampaignSettingTypedDict(TypedDict):
    i_spot_reach_setting: NotRequired[IncrementalReachBrandInputTypedDict]
    realytics_reach_setting: NotRequired[RealyticsReachSettingInputTypedDict]
    tv_squared_reach_setting: NotRequired[IncrementalReachBrandInputTypedDict]
    samba_au_reach_setting: NotRequired[IncrementalReachBrandInputTypedDict]


class CampaignCreateWorkflowIncrementalReachCampaignSetting(BaseModel):
    i_spot_reach_setting: Annotated[
        Optional[IncrementalReachBrandInput], pydantic.Field(alias="iSpotReachSetting")
    ] = None

    realytics_reach_setting: Annotated[
        Optional[RealyticsReachSettingInput],
        pydantic.Field(alias="realyticsReachSetting"),
    ] = None

    tv_squared_reach_setting: Annotated[
        Optional[IncrementalReachBrandInput],
        pydantic.Field(alias="tvSquaredReachSetting"),
    ] = None

    samba_au_reach_setting: Annotated[
        Optional[IncrementalReachBrandInput],
        pydantic.Field(alias="sambaAuReachSetting"),
    ] = None
