"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgroupworkflow import AdGroupWorkflow, AdGroupWorkflowTypedDict
from .campaignworkflow import CampaignWorkflow, CampaignWorkflowTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignPayloadTypedDict(TypedDict):
    campaign: NotRequired[CampaignWorkflowTypedDict]
    ad_groups: NotRequired[Nullable[List[AdGroupWorkflowTypedDict]]]


class CampaignPayload(BaseModel):
    campaign: Optional[CampaignWorkflow] = None

    ad_groups: Annotated[
        OptionalNullable[List[AdGroupWorkflow]], pydantic.Field(alias="adGroups")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["campaign", "adGroups"]
        nullable_fields = ["adGroups"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
