"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaigncreateworkflowinput import (
    CampaignCreateWorkflowInput,
    CampaignCreateWorkflowInputTypedDict,
)
from .workflowcallbackinput import WorkflowCallbackInput, WorkflowCallbackInputTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignBulkCreateWorkflowInputWithValidationTypedDict(TypedDict):
    input: Nullable[List[CampaignCreateWorkflowInputTypedDict]]
    validate_input_only: NotRequired[Nullable[bool]]
    callback_input: NotRequired[WorkflowCallbackInputTypedDict]


class CampaignBulkCreateWorkflowInputWithValidation(BaseModel):
    input: Nullable[List[CampaignCreateWorkflowInput]]

    validate_input_only: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="validateInputOnly")
    ] = UNSET

    callback_input: Annotated[
        Optional[WorkflowCallbackInput], pydantic.Field(alias="callbackInput")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["validateInputOnly", "callbackInput"])
        nullable_fields = set(["input", "validateInputOnly"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignBulkCreateWorkflowInputWithValidation.model_rebuild()
except NameError:
    pass
