"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaigncreateworkflowadgroupinput import (
    CampaignCreateWorkflowAdGroupInput,
    CampaignCreateWorkflowAdGroupInputTypedDict,
)
from .campaigncreateworkflowprimaryinput import (
    CampaignCreateWorkflowPrimaryInput,
    CampaignCreateWorkflowPrimaryInputTypedDict,
)
from .campaignworkflowadvancedinput import (
    CampaignWorkflowAdvancedInput,
    CampaignWorkflowAdvancedInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowInputTypedDict(TypedDict):
    primary_input: CampaignCreateWorkflowPrimaryInputTypedDict
    advanced_input: NotRequired[CampaignWorkflowAdvancedInputTypedDict]
    ad_groups: NotRequired[Nullable[List[CampaignCreateWorkflowAdGroupInputTypedDict]]]
    validate_input_only: NotRequired[Nullable[bool]]


class CampaignCreateWorkflowInput(BaseModel):
    primary_input: Annotated[
        CampaignCreateWorkflowPrimaryInput, pydantic.Field(alias="primaryInput")
    ]

    advanced_input: Annotated[
        Optional[CampaignWorkflowAdvancedInput], pydantic.Field(alias="advancedInput")
    ] = None

    ad_groups: Annotated[
        OptionalNullable[List[CampaignCreateWorkflowAdGroupInput]],
        pydantic.Field(alias="adGroups"),
    ] = UNSET

    validate_input_only: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="validateInputOnly")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["advancedInput", "adGroups", "validateInputOnly"]
        nullable_fields = ["adGroups", "validateInputOnly"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
