"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .audienceunlimitedtierinput import AudienceUnlimitedTierInput
from .tradingmodecreateinput import TradingModeCreateInput
import pydantic
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowTradingModeSettingsInputTypedDict(TypedDict):
    mode: NotRequired[TradingModeCreateInput]
    audience_unlimited_tier: NotRequired[AudienceUnlimitedTierInput]


class CampaignCreateWorkflowTradingModeSettingsInput(BaseModel):
    mode: Optional[TradingModeCreateInput] = None

    audience_unlimited_tier: Annotated[
        Optional[AudienceUnlimitedTierInput],
        pydantic.Field(alias="audienceUnlimitedTier"),
    ] = None
