"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaigncreateworkflowadgroupinput import (
    CampaignCreateWorkflowAdGroupInput,
    CampaignCreateWorkflowAdGroupInputTypedDict,
)
from .campaigncreateworkflowadvancedinput import (
    CampaignCreateWorkflowAdvancedInput,
    CampaignCreateWorkflowAdvancedInputTypedDict,
)
from .campaigncreateworkflowprimaryinput import (
    CampaignCreateWorkflowPrimaryInput,
    CampaignCreateWorkflowPrimaryInputTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CampaignCreateWorkflowInputWithValidationTypedDict(TypedDict):
    primary_input: CampaignCreateWorkflowPrimaryInputTypedDict
    advanced_input: NotRequired[CampaignCreateWorkflowAdvancedInputTypedDict]
    ad_groups: NotRequired[Nullable[List[CampaignCreateWorkflowAdGroupInputTypedDict]]]
    validate_input_only: NotRequired[Nullable[bool]]


class CampaignCreateWorkflowInputWithValidation(BaseModel):
    primary_input: Annotated[
        CampaignCreateWorkflowPrimaryInput, pydantic.Field(alias="primaryInput")
    ]

    advanced_input: Annotated[
        Optional[CampaignCreateWorkflowAdvancedInput],
        pydantic.Field(alias="advancedInput"),
    ] = None

    ad_groups: Annotated[
        OptionalNullable[List[CampaignCreateWorkflowAdGroupInput]],
        pydantic.Field(alias="adGroups"),
    ] = UNSET

    validate_input_only: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="validateInputOnly")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["advancedInput", "adGroups", "validateInputOnly"])
        nullable_fields = set(["adGroups", "validateInputOnly"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CampaignCreateWorkflowInputWithValidation.model_rebuild()
except NameError:
    pass
