"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .adgrouppayload import AdGroupPayload, AdGroupPayloadTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateAdGroupResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    ad_group_payload: NotRequired[AdGroupPayloadTypedDict]
    r"""Created"""


class CreateAdGroupResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    ad_group_payload: Optional[AdGroupPayload] = None
    r"""Created"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["AdGroupPayload"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
