"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class CustomROASType(str, Enum):
    DISABLED = "Disabled"
    PIXEL_WEIGHTING = "PixelWeighting"
    CLICK_VIEWTHROUGH_WEIGHTING = "ClickViewthroughWeighting"
    COMPOSITE_WEIGHTING = "CompositeWeighting"
