"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class CustomROASConfigTypedDict(TypedDict):
    include_in_custom_roas: bool
    custom_roas_weight: NotRequired[Nullable[float]]
    custom_roas_click_weight: NotRequired[Nullable[float]]
    custom_roas_viewthrough_weight: NotRequired[Nullable[float]]


class CustomROASConfig(BaseModel):
    include_in_custom_roas: Annotated[bool, pydantic.Field(alias="includeInCustomROAS")]

    custom_roas_weight: Annotated[
        OptionalNullable[float], pydantic.Field(alias="customROASWeight")
    ] = UNSET

    custom_roas_click_weight: Annotated[
        OptionalNullable[float], pydantic.Field(alias="customROASClickWeight")
    ] = UNSET

    custom_roas_viewthrough_weight: Annotated[
        OptionalNullable[float], pydantic.Field(alias="customROASViewthroughWeight")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["customROASWeight", "customROASClickWeight", "customROASViewthroughWeight"]
        )
        nullable_fields = set(
            ["customROASWeight", "customROASClickWeight", "customROASViewthroughWeight"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CustomROASConfig.model_rebuild()
except NameError:
    pass
