"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DeviceType(str, Enum):
    UNKNOWN = "Unknown"
    OTHER = "Other"
    PC = "PC"
    TABLET = "Tablet"
    MOBILE = "Mobile"
    ROKU = "Roku"
    CONNECTED_TV = "ConnectedTV"
    OUT_OF_HOME = "OutOfHome"
    HOME_ASSISTANT = "HomeAssistant"
