"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DoubleVerifyVideoViewability(str, Enum):
    DURATION10 = "Duration10"
    DURATION20 = "Duration20"
    DURATION25 = "Duration25"
    DURATION30 = "Duration30"
    DURATION35 = "Duration35"
    DURATION40 = "Duration40"
    VIEWABILITY30 = "Viewability30"
    VIEWABILITY40 = "Viewability40"
    VIEWABILITY50 = "Viewability50"
    VIEWABILITY55 = "Viewability55"
    VIEWABILITY60 = "Viewability60"
    VIEWABILITY65 = "Viewability65"
    VIEWABILITY70 = "Viewability70"
    VIEWABILITY75 = "Viewability75"
    VIEWABILITY80 = "Viewability80"
