"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DoubleVerifyBotAvoidance(str, Enum):
    FRAUD_INVALID = "FraudInvalid"
    FRAUD_NO_ADS = "FraudNoAds"
