"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing_extensions import Annotated, NotRequired, TypedDict


class FactualProximityTargetInputTypedDict(TypedDict):
    targeting_code_id: NotRequired[Nullable[int]]
    design_id: NotRequired[Nullable[int]]


class FactualProximityTargetInput(BaseModel):
    targeting_code_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="targetingCodeId")
    ] = UNSET

    design_id: Annotated[OptionalNullable[int], pydantic.Field(alias="designId")] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["targetingCodeId", "designId"])
        nullable_fields = set(["targetingCodeId", "designId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    FactualProximityTargetInput.model_rebuild()
except NameError:
    pass
