"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.types import BaseModel
from typing_extensions import Annotated, TypedDict


class FirstPartyDataInputTypedDict(TypedDict):
    r"""Required fields for submitting a bulk job for first party data"""

    advertiser_id: str
    r"""The advertiser id to query for."""


class FirstPartyDataInput(BaseModel):
    r"""Required fields for submitting a bulk job for first party data"""

    advertiser_id: Annotated[str, pydantic.Field(alias="advertiserId")]
    r"""The advertiser id to query for."""
