"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .int32range import Int32Range, Int32RangeTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FrequencyAdjustmentInputTypedDict(TypedDict):
    counter_id: NotRequired[Nullable[str]]
    times_shown: NotRequired[Int32RangeTypedDict]


class FrequencyAdjustmentInput(BaseModel):
    counter_id: Annotated[OptionalNullable[str], pydantic.Field(alias="counterId")] = (
        UNSET
    )

    times_shown: Annotated[Optional[Int32Range], pydantic.Field(alias="timesShown")] = (
        None
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["counterId", "timesShown"])
        nullable_fields = set(["counterId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    FrequencyAdjustmentInput.model_rebuild()
except NameError:
    pass
