"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class FrequencyConfigTypedDict(TypedDict):
    counter_name: NotRequired[Nullable[str]]
    frequency_cap: NotRequired[Nullable[int]]
    frequency_goal: NotRequired[Nullable[int]]
    reset_interval_in_minutes: NotRequired[int]


class FrequencyConfig(BaseModel):
    counter_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="counterName")
    ] = UNSET

    frequency_cap: Annotated[
        OptionalNullable[int], pydantic.Field(alias="frequencyCap")
    ] = UNSET

    frequency_goal: Annotated[
        OptionalNullable[int], pydantic.Field(alias="frequencyGoal")
    ] = UNSET

    reset_interval_in_minutes: Annotated[
        Optional[int], pydantic.Field(alias="resetIntervalInMinutes")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["counterName", "frequencyCap", "frequencyGoal", "resetIntervalInMinutes"]
        )
        nullable_fields = set(["counterName", "frequencyCap", "frequencyGoal"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    FrequencyConfig.model_rebuild()
except NameError:
    pass
