"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class FullReferrerURL(str, Enum):
    UNKNOWN = "Unknown"
    DOMAIN_ONLY = "DomainOnly"
    FULL_URL = "FullUrl"
