"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ttd_workflows.types import BaseModel
from ttd_workflows.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class GetTypebasedjobIDStatusRequestTypedDict(TypedDict):
    id: int


class GetTypebasedjobIDStatusRequest(BaseModel):
    id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
