"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graphqlbulkjobretrievalresponse import (
    GraphQLBulkJobRetrievalResponse,
    GraphQLBulkJobRetrievalResponseTypedDict,
)
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, UNSET_SENTINEL
from ttd_workflows.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetGraphQlBulkJobStatusRequestTypedDict(TypedDict):
    id: str


class GetGraphQlBulkJobStatusRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetGraphQlBulkJobStatusResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    graph_ql_bulk_job_retrieval_response: NotRequired[
        GraphQLBulkJobRetrievalResponseTypedDict
    ]
    r"""OK"""


class GetGraphQlBulkJobStatusResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    graph_ql_bulk_job_retrieval_response: Optional[GraphQLBulkJobRetrievalResponse] = (
        None
    )
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["GraphQLBulkJobRetrievalResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
