"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict, List
from typing_extensions import Annotated, NotRequired, TypedDict


class GraphQLBulkJobErrorTypedDict(TypedDict):
    r"""Represents an error type returned by the inner data on a mutation response"""

    message: Nullable[str]
    field: NotRequired[Nullable[List[str]]]
    additional_data: NotRequired[Nullable[Dict[str, str]]]


class GraphQLBulkJobError(BaseModel):
    r"""Represents an error type returned by the inner data on a mutation response"""

    message: Nullable[str]

    field: OptionalNullable[List[str]] = UNSET

    additional_data: Annotated[
        OptionalNullable[Dict[str, str]], pydantic.Field(alias="additionalData")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["field", "additionalData"])
        nullable_fields = set(["message", "field", "additionalData"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    GraphQLBulkJobError.model_rebuild()
except NameError:
    pass
