"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class IdiosyncraticSegment(str, Enum):
    NONE = "None"
    ALL_KNOWN_HOUSEHOLDS = "AllKnownHouseholds"
    LIGHT_TV_VIEWERS = "LightTvViewers"
    LIGHT_TV_VIEWERS2 = "LightTvViewers2"
