"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class IntegralViewabilityInput(str, Enum):
    IN_VIEW40 = "InView40"
    IN_VIEW50 = "InView50"
    IN_VIEW60 = "InView60"
    IN_VIEW70 = "InView70"
