"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, Nullable, UNSET_SENTINEL
from typing_extensions import TypedDict


class KeyValuePairOfStringAndStringInputTypedDict(TypedDict):
    r"""Type that specifies the key value association of a callback header."""

    key: Nullable[str]
    value: Nullable[str]


class KeyValuePairOfStringAndStringInput(BaseModel):
    r"""Type that specifies the key value association of a callback header."""

    key: Nullable[str]

    value: Nullable[str]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
