"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class MarketType(str, Enum):
    OPEN_MARKET = "OpenMarket"
    PRIVATE_MARKET_ONLY = "PrivateMarketOnly"
    MARKETPLACE = "Marketplace"
