"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class MultipleMatchResolutionType(str, Enum):
    SINGLE_MATCH_ONLY = "SingleMatchOnly"
    APPLY_MINIMUM_ADJUSTMENT = "ApplyMinimumAdjustment"
    APPLY_AVERAGE_ADJUSTMENT = "ApplyAverageAdjustment"
    APPLY_MAXIMUM_ADJUSTMENT = "ApplyMaximumAdjustment"
    APPLY_MULTIPLY_ADJUSTMENT = "ApplyMultiplyAdjustment"
