"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class NativePlacementType(str, Enum):
    UNKNOWN = "Unknown"
    IN_FEED = "InFeed"
    INSIDE_CONTENT = "InsideContent"
    OUTSIDE_CONTENT = "OutsideContent"
    RECOMMENDATION_WIDGET = "RecommendationWidget"
