"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class NativeContextType(str, Enum):
    UNCLASSIFIED = "Unclassified"
    CONTENT = "Content"
    SOCIAL = "Social"
    PRODUCT = "Product"
    CONTENT_UNCLASSIFIED = "ContentUnclassified"
    SOCIAL_UNCLASSIFIED = "SocialUnclassified"
    PRODUCT_UNCLASSIFIED = "ProductUnclassified"
    GENERAL = "General"
    ARTICLE = "Article"
    VIDEO = "Video"
    AUDIO = "Audio"
    IMAGE = "Image"
    USER_GENERATED = "UserGenerated"
    GENERAL_SOCIAL = "GeneralSocial"
    EMAIL = "Email"
    CHAT_OR_IM = "ChatOrIM"
    SELLING_PRODUCTS = "SellingProducts"
    APPLICATION_STORE = "ApplicationStore"
    PRODUCT_REVIEW = "ProductReview"
