"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PassThroughFeeType(str, Enum):
    NONE = "None"
    MEDIA_COST_PERCENTAGE = "MediaCostPercentage"
    DATA_COST_PERCENTAGE = "DataCostPercentage"
    MEDIA_PLUS_DATA_COST_PERCENTAGE = "MediaPlusDataCostPercentage"
    PARTNER_DATA_COST_PERCENTAGE = "PartnerDataCostPercentage"
    FEE_CPM = "FeeCPM"
    RATE_CPM = "RateCPM"
    RATE_CPC = "RateCPC"
    CUSTOM_PMP_PARTNER_DATA_COST_PERCENTAGE = "CustomPmpPartnerDataCostPercentage"
