"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class Peer39ViewabilityInput(str, Enum):
    TOP60 = "Top60"
    TOP80 = "Top80"
