"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .problemdetails import ProblemDetails
import pydantic
from ttd_workflows import utils
from ttd_workflows.types import BaseModel, OptionalNullable, UNSET
from typing import Dict, Optional
from typing_extensions import Annotated


class ProblemDetailsErrorData(BaseModel):
    type: OptionalNullable[str] = UNSET

    title: OptionalNullable[str] = UNSET

    status: OptionalNullable[int] = UNSET

    detail: OptionalNullable[str] = UNSET

    instance: OptionalNullable[str] = UNSET

    additional_properties: Annotated[
        Optional[Dict[str, ProblemDetails]], pydantic.Field(exclude=True)
    ] = None


class ProblemDetailsError(Exception):
    data: ProblemDetailsErrorData

    def __init__(self, data: ProblemDetailsErrorData):
        self.data = data

    def __str__(self) -> str:
        return utils.marshal_json(self.data, ProblemDetailsErrorData)
