"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .incrementalreachproductinput import (
    IncrementalReachProductInput,
    IncrementalReachProductInputTypedDict,
)
from .realyticsentertainmenttype import RealyticsEntertainmentType
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RealyticsReachSettingInputTypedDict(TypedDict):
    id: NotRequired[int]
    name: NotRequired[Nullable[str]]
    is_active: NotRequired[bool]
    products: NotRequired[Nullable[List[IncrementalReachProductInputTypedDict]]]
    realytics_entertainment_input: NotRequired[RealyticsEntertainmentType]


class RealyticsReachSettingInput(BaseModel):
    id: Optional[int] = None

    name: OptionalNullable[str] = UNSET

    is_active: Annotated[Optional[bool], pydantic.Field(alias="isActive")] = None

    products: OptionalNullable[List[IncrementalReachProductInput]] = UNSET

    realytics_entertainment_input: Annotated[
        Optional[RealyticsEntertainmentType],
        pydantic.Field(alias="realyticsEntertainmentInput"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "name", "isActive", "products", "realyticsEntertainmentInput"]
        )
        nullable_fields = set(["name", "products"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    RealyticsReachSettingInput.model_rebuild()
except NameError:
    pass
