"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class RealyticsEntertainmentType(str, Enum):
    IPTV = "IPTV"
    CTV = "CTV"
    TVS = "TVS"
