"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .seedtargetingdatainput import (
    SeedTargetingDataInput,
    SeedTargetingDataInputTypedDict,
)
import pydantic
from ttd_workflows.types import BaseModel
from typing_extensions import Annotated, TypedDict


class SeedCreationInputTypedDict(TypedDict):
    r"""Required fields for creating a new seed"""

    advertiser_id: str
    r"""The platform ID of the advertiser that owns this Seed."""
    seed_name: str
    r"""The name of the Seed."""
    is_default: bool
    r"""Whether this is the default seed for this advertiser"""
    targeting_data: SeedTargetingDataInputTypedDict


class SeedCreationInput(BaseModel):
    r"""Required fields for creating a new seed"""

    advertiser_id: Annotated[str, pydantic.Field(alias="advertiserId")]
    r"""The platform ID of the advertiser that owns this Seed."""

    seed_name: Annotated[str, pydantic.Field(alias="seedName")]
    r"""The name of the Seed."""

    is_default: Annotated[bool, pydantic.Field(alias="isDefault")]
    r"""Whether this is the default seed for this advertiser"""

    targeting_data: Annotated[
        SeedTargetingDataInput, pydantic.Field(alias="targetingData")
    ]
