"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.types import BaseModel
from typing_extensions import Annotated, TypedDict


class SharedSeedTypedDict(TypedDict):
    r"""Seed entity"""

    id: int
    r"""Seed ID"""
    seed_name: str
    r"""The name of this seed"""
    advertiser_id: str
    r"""The platform ID of the advertiser that owns this Campaign."""


class SharedSeed(BaseModel):
    r"""Seed entity"""

    id: int
    r"""Seed ID"""

    seed_name: Annotated[str, pydantic.Field(alias="seedName")]
    r"""The name of this seed"""

    advertiser_id: Annotated[str, pydantic.Field(alias="advertiserId")]
    r"""The platform ID of the advertiser that owns this Campaign."""
