"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SharedCampaignTypedDict(TypedDict):
    r"""This is a campaign response"""

    advertiser_id: str
    r"""The platform ID of the advertiser that owns this Campaign."""
    campaign_name: str
    r"""The name of the Campaign."""
    id: NotRequired[int]
    r"""This is a campaign ID"""


class SharedCampaign(BaseModel):
    r"""This is a campaign response"""

    advertiser_id: Annotated[str, pydantic.Field(alias="advertiserId")]
    r"""The platform ID of the advertiser that owns this Campaign."""

    campaign_name: Annotated[str, pydantic.Field(alias="campaignName")]
    r"""The name of the Campaign."""

    id: Optional[int] = None
    r"""This is a campaign ID"""
