"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .graphqlbulkjobresponse import (
    GraphQlBulkJobResponse,
    GraphQlBulkJobResponseTypedDict,
)
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
import pydantic
from ttd_workflows.types import BaseModel
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SubmitGraphQlBulkQueryJobResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    graph_ql_bulk_job_response: NotRequired[GraphQlBulkJobResponseTypedDict]
    r"""OK"""


class SubmitGraphQlBulkQueryJobResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    graph_ql_bulk_job_response: Optional[GraphQlBulkJobResponse] = None
    r"""OK"""
