"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ttd_workflows.types import BaseModel
from typing_extensions import TypedDict


class SubmitGraphQlRequestResponseTypedDict(TypedDict):
    r"""OK"""


class SubmitGraphQlRequestResponse(BaseModel):
    r"""OK"""
