"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class TencentPageQualityInput(str, Enum):
    BLOCK_HIGH_RISK = "BlockHighRisk"
    BLOCK_MODERATE_AND_HIGH_RISK = "BlockModerateAndHighRisk"
