"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .workflowcallbackinput import WorkflowCallbackInput, WorkflowCallbackInputTypedDict
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThirdPartyDataInputTypedDict(TypedDict):
    r"""Required fields for submitting a bulk job for third-party data."""

    partner_id: str
    r"""The partner ID to query for."""
    query_shape: NotRequired[Nullable[str]]
    r"""The shape of the query with the fields being asked for, which is sent downstream.
    This determines what the response will look like.

    For example, a query shape equal to `\"nodes {id name}\"` will return the `id` and `name` fields only.

    If this is not provided the default query shape will be used:

    ```graphql
    nodes {
    id
    name
    providerId
    providerElementId
    description
    buyable
    fullPath
    activeUniques {
    householdCount
    idsConnectedTvCount
    idsInAppCount
    idsWebCount
    personsCount
    thirdPartyDataOverlapCount
    lastUpdated
    }
    }
    ```
    """
    callback_input: NotRequired[WorkflowCallbackInputTypedDict]


class ThirdPartyDataInput(BaseModel):
    r"""Required fields for submitting a bulk job for third-party data."""

    partner_id: Annotated[str, pydantic.Field(alias="partnerId")]
    r"""The partner ID to query for."""

    query_shape: Annotated[
        OptionalNullable[str], pydantic.Field(alias="queryShape")
    ] = UNSET
    r"""The shape of the query with the fields being asked for, which is sent downstream.
    This determines what the response will look like.

    For example, a query shape equal to `\"nodes {id name}\"` will return the `id` and `name` fields only.

    If this is not provided the default query shape will be used:

    ```graphql
    nodes {
    id
    name
    providerId
    providerElementId
    description
    buyable
    fullPath
    activeUniques {
    householdCount
    idsConnectedTvCount
    idsInAppCount
    idsWebCount
    personsCount
    thirdPartyDataOverlapCount
    lastUpdated
    }
    }
    ```
    """

    callback_input: Annotated[
        Optional[WorkflowCallbackInput], pydantic.Field(alias="callbackInput")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["queryShape", "callbackInput"])
        nullable_fields = set(["queryShape"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ThirdPartyDataInput.model_rebuild()
except NameError:
    pass
