"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .campaignpayload import CampaignPayload, CampaignPayloadTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .standardjobsubmitresponse import (
    StandardJobSubmitResponse,
    StandardJobSubmitResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateCampaignsJobResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    standard_job_submit_response: NotRequired[StandardJobSubmitResponseTypedDict]
    r"""Accepted"""
    campaign_payload: NotRequired[CampaignPayloadTypedDict]
    r"""OK"""


class UpdateCampaignsJobResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    standard_job_submit_response: Optional[StandardJobSubmitResponse] = None
    r"""Accepted"""

    campaign_payload: Optional[CampaignPayload] = None
    r"""OK"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["StandardJobSubmitResponse", "CampaignPayload"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
