"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class VideoPlayerSize(str, Enum):
    UNUSED = "UNUSED"
    UNKNOWN = "Unknown"
    SMALL = "Small"
    MEDIUM = "Medium"
    LARGE = "Large"
    IN_BANNER = "InBanner"
