"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class WeatherCondition(str, Enum):
    THUNDERSTORM = "Thunderstorm"
    DRIZZLE = "Drizzle"
    RAIN = "Rain"
    SNOW = "Snow"
    MIST = "Mist"
    SMOKE = "Smoke"
    HAZE = "Haze"
    DUST = "Dust"
    FOG = "Fog"
    SAND = "Sand"
    ASH = "Ash"
    SQUALL = "Squall"
    TORNADO = "Tornado"
    CLEAR = "Clear"
    CLOUDS = "Clouds"
    WIND = "Wind"
