"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_workflows.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import Dict
from typing_extensions import Annotated, NotRequired, TypedDict


class WorkflowCallbackInputTypedDict(TypedDict):
    callback_url: str
    callback_headers: NotRequired[Nullable[Dict[str, str]]]


class WorkflowCallbackInput(BaseModel):
    callback_url: Annotated[str, pydantic.Field(alias="callbackUrl")]

    callback_headers: Annotated[
        OptionalNullable[Dict[str, str]], pydantic.Field(alias="callbackHeaders")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["callbackHeaders"])
        nullable_fields = set(["callbackHeaders"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    WorkflowCallbackInput.model_rebuild()
except NameError:
    pass
