overlay: 1.0.0
info:
  title: Speakeasy Configurations
  version: 0.0.1
actions:
  - target: $.servers[0]
    remove: true
  - target: $.servers
    update:
      - url: https://api.thetradedesk.com/workflows
        description: "A RESTful service for commonly used workflows."
  - target: $
    update:
      x-speakeasy-retries:
        strategy: backoff
        backoff:
          initialInterval: 500
          maxInterval: 60000
          maxElapsedTime: 3600000
          exponent: 1.5
        statusCodes: 
          - 5XX
        retryConnectionErrors: true