overlay: 1.0.0
info:
  title: Speakeasy Configurations
  version: 0.0.1
actions:
  - target: $
    update:
      servers:
        - url: https://api.thetradedesk.com/workflows
          description: "The production environment."
          x-speakeasy-server-id: prod
        - url: https://ext-api.sb.thetradedesk.com/workflows
          description: "The sandbox environment for testing."
          x-speakeasy-server-id: sandbox
  - target: $
    update:
      x-speakeasy-retries:
        strategy: backoff
        backoff:
          initialInterval: 500
          maxInterval: 60000
          maxElapsedTime: 3600000
          exponent: 1.5
        statusCodes:
          - 5XX
        retryConnectionErrors: true