workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Workflows API:
        inputs:
            - location: https://api.thetradedesk.com/workflows/swagger/v1/swagger.yaml
              authHeader: TTD-Auth
              authSecret: $openapi_doc_auth_token
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: .speakeasy/speakeasy-config-overlay.yaml
            - location: .speakeasy/api-spec-overlay.yaml
        output: combined_api_spec.yaml
        registry:
            location: registry.speakeasyapi.dev/thetradedesk/workflows/workflows-api
targets:
    workflows:
        target: python
        source: Workflows API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/thetradedesk/workflows/workflows-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
